zpp: zpp::futex_base< T_Futex > Class Template Reference
zpp::futex_base< T_Futex > Class Template Reference
A CRTP futex base class.
#include <futex.hpp>
Public Types
using native_type = struct k_futex
using native_pointer = native_type *
using native_const_pointer = native_type const *
Public Member Functions
bool wait (int expected) noexcept
Wait for the futex.
bool try_wait (int expected) noexcept
Try wait for the futex.
template<class T_Rep , class T_Period >
bool try_wait_for (int expected, const std::chrono::duration< T_Rep, T_Period > &timeout) noexcept
Wait for the futex.
void wake_one () noexcept
Wakeup one waiting thread.
void wake_all () noexcept
Wakeup all waiting threads.
auto native_handle () noexcept -> native_pointer
get the native zephyr futex handle.
auto native_handle () const noexcept -> native_const_pointer
get the native zephyr futex handle.
futex_base (const futex_base &)=delete
futex_base (futex_base &&)=delete
futex_base & operator= (const futex_base &)=delete
futex_base & operator= (futex_base &&)=delete
Protected Member Functions
constexpr futex_base () noexcept
Default constructor.
Detailed Description
template<typename T_Futex>
class zpp::futex_base< T_Futex >
A CRTP futex base class.
Definition at line 23 of file futex.hpp.
Member Typedef Documentation
native_const_pointer
template<typename T_Futex > using zpp::futex_base< T_Futex >::native_const_pointer = native_type const *
Definition at line 28 of file futex.hpp.
native_pointer
template<typename T_Futex > using zpp::futex_base< T_Futex >::native_pointer = native_type *
Definition at line 27 of file futex.hpp.
native_type
template<typename T_Futex > using zpp::futex_base< T_Futex >::native_type = struct k_futex
Definition at line 26 of file futex.hpp.
Constructor & Destructor Documentation
futex_base() [1/3]
template<typename T_Futex > constexpr zpp::futex_base< T_Futex >::futex_base () inline constexpr protected noexcept
Default constructor.
Definition at line 33 of file futex.hpp.
   {
   }
futex_base() [2/3]
template<typename T_Futex > zpp::futex_base< T_Futex >::futex_base (const futex_base< T_Futex > &) delete
futex_base() [3/3]
template<typename T_Futex > zpp::futex_base< T_Futex >::futex_base (futex_base< T_Futex > &&) delete
Member Function Documentation
native_handle() [1/2]
template<typename T_Futex > auto zpp::futex_base< T_Futex >::native_handle () const -> native_const_pointer inline noexcept
get the native zephyr futex handle.
Returns
A pointer to the zephyr k_futex.
Definition at line 123 of file futex.hpp.
   {
     return static_cast<const T_Futex*>(this)->native_handle();
   }
References zpp::futex_base< T_Futex >::native_handle().
native_handle() [2/2]
template<typename T_Futex > auto zpp::futex_base< T_Futex >::native_handle () -> native_pointer inline noexcept
get the native zephyr futex handle.
Returns
A pointer to the zephyr k_futex.
Definition at line 113 of file futex.hpp.
   {
     return static_cast<T_Futex*>(this)->native_handle();
   }
Referenced by zpp::futex_base< T_Futex >::native_handle(), zpp::futex_base< T_Futex >::try_wait(), zpp::futex_base< T_Futex >::try_wait_for(), zpp::futex_base< T_Futex >::wait(), zpp::futex_base< T_Futex >::wake_all(), and zpp::futex_base< T_Futex >::wake_one().
operator=() [1/2]
template<typename T_Futex > futex_base& zpp::futex_base< T_Futex >::operator= (const futex_base< T_Futex > &) delete
operator=() [2/2]
template<typename T_Futex > futex_base& zpp::futex_base< T_Futex >::operator= (futex_base< T_Futex > &&) delete
try_wait()
template<typename T_Futex > bool zpp::futex_base< T_Futex >::try_wait (int expected) inline noexcept
Try wait for the futex.
Parameters
expected the expected value
Returns
true if successfull
Definition at line 61 of file futex.hpp.
   {
     if (futex_wait(native_handle(), expected, K_NO_WAIT) == 0) {
       return true;
     } else {
       return false;
     }
   }
References zpp::futex_base< T_Futex >::native_handle().
try_wait_for()
template<typename T_Futex > template<class T_Rep , class T_Period > bool zpp::futex_base< T_Futex >::try_wait_for (int expected, const std::chrono::duration< T_Rep, T_Period > & timeout) inline noexcept
Wait for the futex.
Parameters
expected the expected value
timeout the timeout before returning
Returns
true if successfull
Definition at line 80 of file futex.hpp.
   {
     using namespace std::chrono;
     if (futex_wait(native_handle(), expected, to_timeout(timeout)) == 0)
     {
       return true;
     } else {
       return false;
     }
   }
References zpp::futex_base< T_Futex >::native_handle(), and zpp::to_timeout().
wait()
template<typename T_Futex > bool zpp::futex_base< T_Futex >::wait (int expected) inline noexcept
Wait for the futex.
Parameters
expected the expected value
Returns
true if successfull
Definition at line 45 of file futex.hpp.
   {
     if (futex_wait(native_handle(), expected, K_FOREVER) == 0) {
       return true;
     } else {
       return false;
     }
   }
References zpp::futex_base< T_Futex >::native_handle().
wake_all()
template<typename T_Futex > void zpp::futex_base< T_Futex >::wake_all () inline noexcept
Wakeup all waiting threads.
Definition at line 103 of file futex.hpp.
   {
     futex_wake(native_handle(), true);
   }
References zpp::futex_base< T_Futex >::native_handle().
wake_one()
template<typename T_Futex > void zpp::futex_base< T_Futex >::wake_one () inline noexcept
Wakeup one waiting thread.
Definition at line 95 of file futex.hpp.
   {
     futex_wake(native_handle(), false);
   }
References zpp::futex_base< T_Futex >::native_handle().
The documentation for this class was generated from the following file:
include/zpp/futex.hpp