zpp: zpp::sem_base< T_Sem > Class Template Reference
zpp::sem_base< T_Sem > Class Template Reference
Counting semaphore base class.
#include <sem.hpp>
Public Types
using native_type = struct k_sem
using native_pointer = native_type *
using native_const_pointer = native_type const *
using counter_type = uint32_t
Type used as counter.
Public Member Functions
bool take () noexcept
Take the semaphore waiting forever.
bool try_take () noexcept
Try to take the semaphore without waiting.
template<class T_Rep , class T_Period >
bool try_take_for (const std::chrono::duration< T_Rep, T_Period > &timeout_duration) noexcept
Try to take the semaphore waiting a certain timeout.
void give () noexcept
Give the semaphore.
void reset () noexcept
Reset the semaphore counter to zero.
counter_type count () noexcept
Get current semaphore count.
void operator++ (int) noexcept
Give the semaphore.
void operator-- (int) noexcept
Take the semaphore waiting forever.
void operator+= (int n) noexcept
Give the semaphore n times.
void operator-= (int n) noexcept
Take the semaphore n times, waiting forever.
auto native_handle () noexcept -> native_pointer
get the native zephyr sem handle.
auto native_handle () const noexcept -> native_const_pointer
get the native zephyr sem handle.
sem_base (const sem_base &)=delete
sem_base (sem_base &&)=delete
sem_base & operator= (const sem_base &)=delete
sem_base & operator= (sem_base &&)=delete
Static Public Attributes
constexpr static counter_type max_count
Maximum value of the counter.
Protected Member Functions
constexpr sem_base () noexcept
Default constructor, only allowed derived objects.
Detailed Description
template<typename T_Sem>
class zpp::sem_base< T_Sem >
Counting semaphore base class.
Definition at line 24 of file sem.hpp.
Member Typedef Documentation
counter_type
template<typename T_Sem > using zpp::sem_base< T_Sem >::counter_type = uint32_t
Type used as counter.
Definition at line 34 of file sem.hpp.
native_const_pointer
template<typename T_Sem > using zpp::sem_base< T_Sem >::native_const_pointer = native_type const *
Definition at line 29 of file sem.hpp.
native_pointer
template<typename T_Sem > using zpp::sem_base< T_Sem >::native_pointer = native_type*
Definition at line 28 of file sem.hpp.
native_type
template<typename T_Sem > using zpp::sem_base< T_Sem >::native_type = struct k_sem
Definition at line 27 of file sem.hpp.
Constructor & Destructor Documentation
sem_base() [1/3]
template<typename T_Sem > constexpr zpp::sem_base< T_Sem >::sem_base () inline constexpr protected noexcept
Default constructor, only allowed derived objects.
Definition at line 45 of file sem.hpp.
   {
   }
sem_base() [2/3]
template<typename T_Sem > zpp::sem_base< T_Sem >::sem_base (const sem_base< T_Sem > &) delete
sem_base() [3/3]
template<typename T_Sem > zpp::sem_base< T_Sem >::sem_base (sem_base< T_Sem > &&) delete
Member Function Documentation
count()
template<typename T_Sem > counter_type zpp::sem_base< T_Sem >::count () inline noexcept
Get current semaphore count.
Returns
The current semaphore count.
Definition at line 117 of file sem.hpp.
   {
     return k_sem_count_get(native_handle());
   }
References zpp::sem_base< T_Sem >::native_handle().
give()
template<typename T_Sem > void zpp::sem_base< T_Sem >::give () inline noexcept
Give the semaphore.
Definition at line 99 of file sem.hpp.
   {
     k_sem_give(native_handle());
   }
References zpp::sem_base< T_Sem >::native_handle().
Referenced by zpp::sem_base< T_Sem >::operator++(), and zpp::sem_base< T_Sem >::operator+=().
native_handle() [1/2]
template<typename T_Sem > auto zpp::sem_base< T_Sem >::native_handle () const -> native_const_pointer inline noexcept
get the native zephyr sem handle.
Returns
A pointer to the zephyr k_sem.
Definition at line 181 of file sem.hpp.
   {
     return static_cast<const T_Sem*>(this)->native_handle();
   }
References zpp::sem_base< T_Sem >::native_handle().
native_handle() [2/2]
template<typename T_Sem > auto zpp::sem_base< T_Sem >::native_handle () -> native_pointer inline noexcept
get the native zephyr sem handle.
Returns
A pointer to the zephyr k_sem.
Definition at line 171 of file sem.hpp.
   {
     return static_cast<T_Sem*>(this)->native_handle();
   }
Referenced by zpp::sem_base< T_Sem >::count(), zpp::sem_base< T_Sem >::give(), zpp::sem_base< T_Sem >::native_handle(), zpp::sem_base< T_Sem >::reset(), zpp::sem_base< T_Sem >::take(), zpp::sem_base< T_Sem >::try_take(), and zpp::sem_base< T_Sem >::try_take_for().
operator++()
template<typename T_Sem > void zpp::sem_base< T_Sem >::operator++ (int) inline noexcept
Give the semaphore.
Definition at line 125 of file sem.hpp.
   {
     give();
   }
References zpp::sem_base< T_Sem >::give().
operator+=()
template<typename T_Sem > void zpp::sem_base< T_Sem >::operator+= (int n) inline noexcept
Give the semaphore n times.
Parameters
n The number of times to give the semaphore
Definition at line 145 of file sem.hpp.
   {
     while (n-- > 0) {
       give();
     }
   }
References zpp::sem_base< T_Sem >::give().
operator--()
template<typename T_Sem > void zpp::sem_base< T_Sem >::operator-- (int) inline noexcept
Take the semaphore waiting forever.
Definition at line 133 of file sem.hpp.
   {
     while (!take()) {
       this_thread::yield();
     }
   }
References zpp::sem_base< T_Sem >::take(), and zpp::this_thread::yield().
operator-=()
template<typename T_Sem > void zpp::sem_base< T_Sem >::operator-= (int n) inline noexcept
Take the semaphore n times, waiting forever.
Parameters
n The number of times to take the semaphore
Definition at line 157 of file sem.hpp.
   {
     while (n-- > 0) {
       while (!take()) {
         this_thread::yield();
       }
     }
   }
References zpp::sem_base< T_Sem >::take(), and zpp::this_thread::yield().
operator=() [1/2]
template<typename T_Sem > sem_base& zpp::sem_base< T_Sem >::operator= (const sem_base< T_Sem > &) delete
operator=() [2/2]
template<typename T_Sem > sem_base& zpp::sem_base< T_Sem >::operator= (sem_base< T_Sem > &&) delete
reset()
template<typename T_Sem > void zpp::sem_base< T_Sem >::reset () inline noexcept
Reset the semaphore counter to zero.
Definition at line 107 of file sem.hpp.
   {
     k_sem_reset(native_handle());
   }
References zpp::sem_base< T_Sem >::native_handle().
take()
template<typename T_Sem > bool zpp::sem_base< T_Sem >::take () inline noexcept
Take the semaphore waiting forever.
Returns
true when semaphore was taken
Definition at line 54 of file sem.hpp.
   {
     if (k_sem_take(native_handle(), K_FOREVER) == 0) {
       return true;
     } else {
       return false;
     }
   }
References zpp::sem_base< T_Sem >::native_handle().
Referenced by zpp::sem_base< T_Sem >::operator--(), and zpp::sem_base< T_Sem >::operator-=().
try_take()
template<typename T_Sem > bool zpp::sem_base< T_Sem >::try_take () inline noexcept
Try to take the semaphore without waiting.
Returns
true when semaphore was taken
Definition at line 68 of file sem.hpp.
   {
     if (k_sem_take(native_handle(), K_NO_WAIT) == 0) {
       return true;
     } else {
       return false;
     }
   }
References zpp::sem_base< T_Sem >::native_handle().
try_take_for()
template<typename T_Sem > template<class T_Rep , class T_Period > bool zpp::sem_base< T_Sem >::try_take_for (const std::chrono::duration< T_Rep, T_Period > & timeout_duration) inline noexcept
Try to take the semaphore waiting a certain timeout.
Parameters
timeout_duration The timeout to wait before giving up
Returns
true when semaphore was taken
Definition at line 86 of file sem.hpp.
   {
     if (k_sem_take(native_handle(), to_timeout(timeout_duration)) == 0) {
       return true;
     } else {
       return false;
     }
   }
References zpp::sem_base< T_Sem >::native_handle(), and zpp::to_timeout().
Member Data Documentation
max_count
template<typename T_Sem > constexpr static counter_type zpp::sem_base< T_Sem >::max_count static constexpr
Initial value:
=
        std::numeric_limits<counter_type>::max()
Maximum value of the counter.
Definition at line 39 of file sem.hpp.
The documentation for this class was generated from the following file:
include/zpp/sem.hpp