zpp: zpp::result< T_Ok, T_Error > Class Template Reference
zpp::result< T_Ok, T_Error > Class Template Reference
result class
#include <result.hpp>
Public Member Functions
result () noexcept
default initialization to error state
result (const T_Ok &rhs) noexcept
initialization to OK state
result (T_Ok &&rhs) noexcept
initialization to OK state
result (const error_result< T_Error > &rhs) noexcept
initialization to error state
result (error_result< T_Error > &&rhs) noexcept
initialization to error state
result (const result &rhs) noexcept
copy contructor
result (result &&rhs) noexcept
move contructor
~result () noexcept
destructor
void assign_value (const T_Ok &v) noexcept
void assign_value (T_Ok &&v) noexcept
void assign_error (const T_Error &e) noexcept
void assign_error (T_Error &&e) noexcept
result & operator= (const result &rhs) noexcept
copy operator
result & operator= (result &&rhs) noexcept
move operator
result & operator= (const T_Ok &rhs) noexcept
copy operator
result & operator= (T_Ok &&rhs) noexcept
move operator
result & operator= (const error_result< T_Error > &rhs) noexcept
copy operator
result & operator= (error_result< T_Error > &&rhs) noexcept
move operator
T_Ok & value () noexcept
return a reference to the OK value
const T_Ok & value () const noexcept
return a const reference to the result value
T_Error & error () noexcept
return a reference to the OK value
const T_Error & error () const noexcept
return a const reference to the result value
T_Ok & operator* () noexcept
return a reference to the result value
const T_Ok & operator* () const noexcept
return a const reference to the result value
T_Ok * operator-> () noexcept
return a pointer to the result value
const T_Ok * operator-> () const noexcept
return a const pointer to the result value
constexpr bool has_value () const noexcept
convert the result to a bool
constexpr operator bool () const noexcept
convert the result to a bool
Detailed Description
template<typename T_Ok, typename T_Error>
class zpp::result< T_Ok, T_Error >
result class
Parameters
T_Ok the type for the OK result
T_Error the type for the error result
Definition at line 89 of file result.hpp.
Constructor & Destructor Documentation
result() [1/7]
template<typename T_Ok , typename T_Error > zpp::result< T_Ok, T_Error >::result () inline noexcept
default initialization to error state
Definition at line 105 of file result.hpp.
     : m_is_ok(false)
   {
     new(&m_error_value) T_Error();
   }
References zpp::result< T_Ok, T_Error >::m_error_value.
result() [2/7]
template<typename T_Ok , typename T_Error > zpp::result< T_Ok, T_Error >::result (const T_Ok & rhs) inline noexcept
initialization to OK state
Parameters
rhs the OK value to assign
Definition at line 116 of file result.hpp.
     : m_is_ok(true)
   {
     new(&m_ok_value) T_Ok(rhs);
   }
References zpp::result< T_Ok, T_Error >::m_ok_value.
result() [3/7]
template<typename T_Ok , typename T_Error > zpp::result< T_Ok, T_Error >::result (T_Ok && rhs) inline noexcept
initialization to OK state
Parameters
rhs the OK value to assign
Definition at line 127 of file result.hpp.
     : m_is_ok(true)
   {
     new(&m_ok_value) T_Ok(std::move(rhs));
   }
References zpp::result< T_Ok, T_Error >::m_ok_value.
result() [4/7]
template<typename T_Ok , typename T_Error > zpp::result< T_Ok, T_Error >::result (const error_result< T_Error > & rhs) inline noexcept
initialization to error state
Parameters
rhs the error value to assign
Definition at line 138 of file result.hpp.
     : m_is_ok(false)
   {
     new(&m_error_value) T_Error(rhs.error());
   }
References zpp::result< T_Ok, T_Error >::m_error_value.
result() [5/7]
template<typename T_Ok , typename T_Error > zpp::result< T_Ok, T_Error >::result (error_result< T_Error > && rhs) inline noexcept
initialization to error state
Parameters
rhs the error value to assign
Definition at line 150 of file result.hpp.
     : m_is_ok(false)
   {
     new(&m_error_value) T_Error(std::move(rhs.error()));
   }
References zpp::result< T_Ok, T_Error >::m_error_value.
result() [6/7]
template<typename T_Ok , typename T_Error > zpp::result< T_Ok, T_Error >::result (const result< T_Ok, T_Error > & rhs) inline noexcept
copy contructor
Parameters
rhs the value to assign
Definition at line 161 of file result.hpp.
     : m_is_ok(rhs.m_is_ok)
   {
     if (m_is_ok) {
       new(&m_ok_value) T_Ok(rhs.m_ok_value);
     } else {
       new(&m_error_value) T_Error(rhs.m_error_value);
     }
   }
References zpp::result< T_Ok, T_Error >::m_error_value, and zpp::result< T_Ok, T_Error >::m_ok_value.
result() [7/7]
template<typename T_Ok , typename T_Error > zpp::result< T_Ok, T_Error >::result (result< T_Ok, T_Error > && rhs) inline noexcept
move contructor
Parameters
rhs the value to assign
Definition at line 176 of file result.hpp.
     : m_is_ok(rhs.m_is_ok)
   {
     if (m_is_ok) {
       new(&m_ok_value) T_Ok(std::move(rhs.m_ok_value));
     } else {
       new(&m_error_value) T_Error(std::move(rhs.m_error_value));
     }
   }
References zpp::result< T_Ok, T_Error >::m_error_value, and zpp::result< T_Ok, T_Error >::m_ok_value.
~result()
template<typename T_Ok , typename T_Error > zpp::result< T_Ok, T_Error >::~result () inline noexcept
destructor
Definition at line 189 of file result.hpp.
                      {
     if (m_is_ok) {
       m_ok_value.~T_Ok();
     } else {
       m_error_value.~T_Error();
     }
   }
References zpp::result< T_Ok, T_Error >::m_error_value, and zpp::result< T_Ok, T_Error >::m_ok_value.
Member Function Documentation
assign_error() [1/2]
template<typename T_Ok , typename T_Error > void zpp::result< T_Ok, T_Error >::assign_error (const T_Error & e) inline noexcept
Definition at line 219 of file result.hpp.
{
     if (m_is_ok) {
       m_ok_value.~T_Ok();
     } else {
       m_error_value.~T_Error();
     }
     m_is_ok = false;
     new(&m_error_value) T_Error(e);
   }
References zpp::result< T_Ok, T_Error >::m_error_value, and zpp::result< T_Ok, T_Error >::m_ok_value.
Referenced by zpp::thread::join(), zpp::mutex_base< T_Mutex >::lock(), zpp::unique_lock< T_Mutex >::lock(), zpp::thread::name(), zpp::condition_variable_base< T_ConditionVariable >::notify_all(), zpp::condition_variable_base< T_ConditionVariable >::notify_one(), zpp::result< void, T_Error >::operator=(), zpp::result< T_Ok, T_Error >::operator=(), zpp::thread::set_name(), zpp::mutex_base< T_Mutex >::try_lock(), zpp::unique_lock< T_Mutex >::try_lock(), zpp::mutex_base< T_Mutex >::try_lock_for(), zpp::unique_lock< T_Mutex >::try_lock_for(), zpp::condition_variable_base< T_ConditionVariable >::try_wait_for(), zpp::mutex_base< T_Mutex >::unlock(), zpp::unique_lock< T_Mutex >::unlock(), and zpp::condition_variable_base< T_ConditionVariable >::wait().
assign_error() [2/2]
template<typename T_Ok , typename T_Error > void zpp::result< T_Ok, T_Error >::assign_error (T_Error && e) inline noexcept
Definition at line 230 of file result.hpp.
{
     if (m_is_ok) {
       m_ok_value.~T_Ok();
     } else {
       m_error_value.~T_Error();
     }
     m_is_ok = false;
     new(&m_error_value) T_Error(std::move(e));
   }
References zpp::result< T_Ok, T_Error >::m_error_value, and zpp::result< T_Ok, T_Error >::m_ok_value.
assign_value() [1/2]
template<typename T_Ok , typename T_Error > void zpp::result< T_Ok, T_Error >::assign_value (const T_Ok & v) inline noexcept
Definition at line 197 of file result.hpp.
{
     if (m_is_ok) {
       m_ok_value.~T_Ok();
     } else {
       m_error_value.~T_Error();
     }
     m_is_ok = true;
     new(&m_ok_value) T_Ok(v);
   }
References zpp::result< T_Ok, T_Error >::m_error_value, and zpp::result< T_Ok, T_Error >::m_ok_value.
Referenced by zpp::thread::abort(), zpp::thread::join(), zpp::mutex_base< T_Mutex >::lock(), zpp::thread::name(), zpp::condition_variable_base< T_ConditionVariable >::notify_all(), zpp::condition_variable_base< T_ConditionVariable >::notify_one(), zpp::result< T_Ok, T_Error >::operator=(), zpp::thread::resume(), zpp::thread::set_name(), zpp::thread::set_priority(), zpp::thread::start(), zpp::thread::suspend(), zpp::mutex_base< T_Mutex >::try_lock(), zpp::mutex_base< T_Mutex >::try_lock_for(), zpp::condition_variable_base< T_ConditionVariable >::try_wait_for(), zpp::mutex_base< T_Mutex >::unlock(), zpp::condition_variable_base< T_ConditionVariable >::wait(), zpp::thread::wakeup(), and ZTEST().
assign_value() [2/2]
template<typename T_Ok , typename T_Error > void zpp::result< T_Ok, T_Error >::assign_value (T_Ok && v) inline noexcept
Definition at line 208 of file result.hpp.
{
     if (m_is_ok) {
       m_ok_value.~T_Ok();
     } else {
       m_error_value.~T_Error();
     }
     m_is_ok = true;
     new(&m_ok_value) T_Ok(std::move(v));
   }
References zpp::result< T_Ok, T_Error >::m_error_value, and zpp::result< T_Ok, T_Error >::m_ok_value.
error() [1/2]
template<typename T_Ok , typename T_Error > const T_Error& zpp::result< T_Ok, T_Error >::error () const inline noexcept
return a const reference to the result value
Returns
T_Ok const reference
Warning
when the result is in error state the the thread will terminate
Definition at line 373 of file result.hpp.
{
     if (m_is_ok) {
       // unhandeld error
     }
     return m_error_value;
   }
References zpp::result< T_Ok, T_Error >::m_error_value.
error() [2/2]
template<typename T_Ok , typename T_Error > T_Error& zpp::result< T_Ok, T_Error >::error () inline noexcept
return a reference to the OK value
Returns
T_Ok reference
Warning
when the result is in error state the the thread will terminate
Definition at line 358 of file result.hpp.
{
     if (m_is_ok) {
       // unhandeld error
     }
     return m_error_value;
   }
References zpp::result< T_Ok, T_Error >::m_error_value.
Referenced by ZTEST().
has_value()
template<typename T_Ok , typename T_Error > constexpr bool zpp::result< T_Ok, T_Error >::has_value () const inline constexpr noexcept
convert the result to a bool
Returns
true if the result is valid
Definition at line 438 of file result.hpp.
{
     return m_is_ok;
   }
operator bool()
template<typename T_Ok , typename T_Error > constexpr zpp::result< T_Ok, T_Error >::operator bool () const inline explicit constexpr noexcept
convert the result to a bool
Returns
true if the result is valid
Definition at line 447 of file result.hpp.
{
     return m_is_ok;
   }
operator*() [1/2]
template<typename T_Ok , typename T_Error > const T_Ok& zpp::result< T_Ok, T_Error >::operator* () const inline noexcept
return a const reference to the result value
Returns
T_Ok const reference
Warning
when the result is in error state the the thread will terminate
Definition at line 399 of file result.hpp.
{
     return value();
   }
References zpp::result< T_Ok, T_Error >::value().
operator*() [2/2]
template<typename T_Ok , typename T_Error > T_Ok& zpp::result< T_Ok, T_Error >::operator* () inline noexcept
return a reference to the result value
Returns
T_Ok reference
Warning
when the result is in error state the the thread will terminate
Definition at line 388 of file result.hpp.
{
     return value();
   }
References zpp::result< T_Ok, T_Error >::value().
operator->() [1/2]
template<typename T_Ok , typename T_Error > const T_Ok* zpp::result< T_Ok, T_Error >::operator-> () const inline noexcept
return a const pointer to the result value
Returns
T_Ok const pointer
Warning
when the result is in error state the the thread will terminate
Definition at line 425 of file result.hpp.
{
     if (!m_is_ok) {
       // unhandeld error
     }
     return &m_ok_value;
   }
References zpp::result< T_Ok, T_Error >::m_ok_value.
operator->() [2/2]
template<typename T_Ok , typename T_Error > T_Ok* zpp::result< T_Ok, T_Error >::operator-> () inline noexcept
return a pointer to the result value
Returns
T_Ok pointer
Warning
when the result is in error state the the thread will terminate
Definition at line 410 of file result.hpp.
{
     if (!m_is_ok) {
       // unhandeld error
     }
     return &m_ok_value;
   }
References zpp::result< T_Ok, T_Error >::m_ok_value.
operator=() [1/6]
template<typename T_Ok , typename T_Error > result& zpp::result< T_Ok, T_Error >::operator= (const error_result< T_Error > & rhs) inline noexcept
copy operator
Parameters
rhs the value to assign
Definition at line 302 of file result.hpp.
   {
     assign_error(rhs.error());
     return *this;
   }
References zpp::result< T_Ok, T_Error >::assign_error().
operator=() [2/6]
template<typename T_Ok , typename T_Error > result& zpp::result< T_Ok, T_Error >::operator= (const result< T_Ok, T_Error > & rhs) inline noexcept
copy operator
Parameters
rhs the value to assign
Definition at line 247 of file result.hpp.
   {
     if (rhs.m_is_ok) {
       assign_value(rhs.m_ok_value);
     } else {
       assign_error(rhs.m_error_value);
     }
     return *this;
   }
References zpp::result< T_Ok, T_Error >::assign_error(), and zpp::result< T_Ok, T_Error >::assign_value().
operator=() [3/6]
template<typename T_Ok , typename T_Error > result& zpp::result< T_Ok, T_Error >::operator= (const T_Ok & rhs) inline noexcept
copy operator
Parameters
rhs the value to assign
Definition at line 280 of file result.hpp.
   {
     assign_value(rhs);
     return *this;
   }
References zpp::result< T_Ok, T_Error >::assign_value().
operator=() [4/6]
template<typename T_Ok , typename T_Error > result& zpp::result< T_Ok, T_Error >::operator= (error_result< T_Error > && rhs) inline noexcept
move operator
Parameters
rhs the value to assign
Definition at line 313 of file result.hpp.
   {
     assign_error(std::move(rhs.error()));
     return *this;
   }
References zpp::result< T_Ok, T_Error >::assign_error().
operator=() [5/6]
template<typename T_Ok , typename T_Error > result& zpp::result< T_Ok, T_Error >::operator= (result< T_Ok, T_Error > && rhs) inline noexcept
move operator
Parameters
rhs the value to assign
Definition at line 263 of file result.hpp.
   {
     if (rhs.m_is_ok) {
       assign_value(std::move(rhs.m_ok_value));
     } else {
       assign_error(std::move(rhs.m_error_value));
     }
     return *this;
   }
References zpp::result< T_Ok, T_Error >::assign_error(), and zpp::result< T_Ok, T_Error >::assign_value().
operator=() [6/6]
template<typename T_Ok , typename T_Error > result& zpp::result< T_Ok, T_Error >::operator= (T_Ok && rhs) inline noexcept
move operator
Parameters
rhs the value to assign
Definition at line 291 of file result.hpp.
   {
     assign_value(std::move(rhs));
     return *this;
   }
References zpp::result< T_Ok, T_Error >::assign_value().
value() [1/2]
template<typename T_Ok , typename T_Error > const T_Ok& zpp::result< T_Ok, T_Error >::value () const inline noexcept
return a const reference to the result value
Returns
T_Ok const reference
Warning
when the result is in error state the the thread will terminate
Definition at line 342 of file result.hpp.
{
     if (!m_is_ok) {
       // unhandeld error
     }
     return m_ok_value;
   }
References zpp::result< T_Ok, T_Error >::m_ok_value.
value() [2/2]
template<typename T_Ok , typename T_Error > T_Ok& zpp::result< T_Ok, T_Error >::value () inline noexcept
return a reference to the OK value
Returns
T_Ok reference
Warning
when the result is in error state the the thread will terminate
Definition at line 327 of file result.hpp.
{
     if (!m_is_ok) {
       // unhandeld error
     }
     return m_ok_value;
   }
References zpp::result< T_Ok, T_Error >::m_ok_value.
Referenced by zpp::result< T_Ok, T_Error >::operator*(), and ZTEST().
Member Data Documentation
m_error_value
template<typename T_Ok , typename T_Error > T_Error zpp::result< T_Ok, T_Error >::m_error_value
Definition at line 453 of file result.hpp.
Referenced by zpp::result< T_Ok, T_Error >::result(), zpp::result< T_Ok, T_Error >::~result(), zpp::result< T_Ok, T_Error >::assign_error(), zpp::result< void, T_Error >::assign_error(), zpp::result< T_Ok, T_Error >::assign_value(), zpp::result< T_Ok, T_Error >::error(), and zpp::result< void, T_Error >::error().
m_ok_value
template<typename T_Ok , typename T_Error > T_Ok zpp::result< T_Ok, T_Error >::m_ok_value
Definition at line 454 of file result.hpp.
Referenced by zpp::result< T_Ok, T_Error >::result(), zpp::result< T_Ok, T_Error >::~result(), zpp::result< T_Ok, T_Error >::assign_error(), zpp::result< T_Ok, T_Error >::assign_value(), zpp::result< T_Ok, T_Error >::operator->(), and zpp::result< T_Ok, T_Error >::value().
The documentation for this class was generated from the following file:
include/zpp/result.hpp