zpp: zpp::thread_prio Class Reference
zpp::thread_prio Class Reference
Thread priority.
#include <thread_prio.hpp>
Public Member Functions
constexpr thread_prio () noexcept
Default constructor initializing priority to zero.
constexpr thread_prio (int prio) noexcept
Constructor initializing priority to prio.
constexpr int native_value () const noexcept
Get the Zephyr native priority value.
Static Public Member Functions
static constexpr thread_prio highest_coop () noexcept
Get the most prior cooperative priority.
static constexpr thread_prio lowest_coop () noexcept
Get the least prior cooperative priority.
static constexpr thread_prio highest_preempt () noexcept
Get the most prior preemptive priority.
static constexpr thread_prio lowest_preempt () noexcept
Get the least prior preemptive priority.
static constexpr thread_prio min_coop_numeric () noexcept
Get the minium coop numeric value.
static constexpr thread_prio max_coop_numeric () noexcept
Get the minium coop numeric value.
static constexpr thread_prio min_preempt_numeric () noexcept
Get the minium preempt numeric value.
static constexpr thread_prio max_preempt_numeric () noexcept
Get the minium preempt numeric value.
static constexpr thread_prio min_numeric () noexcept
Get the minium numeric value.
static constexpr thread_prio max_numeric () noexcept
Get the maxium numeric value.
static constexpr thread_prio coop (int prio) noexcept
Create a cooperative priority value.
static constexpr thread_prio preempt (int prio) noexcept
Create a preemptive priority value.
Detailed Description
Thread priority.
Definition at line 18 of file thread_prio.hpp.
Constructor & Destructor Documentation
thread_prio() [1/2]
constexpr zpp::thread_prio::thread_prio () inline constexpr noexcept
Default constructor initializing priority to zero.
Definition at line 23 of file thread_prio.hpp.
   {
   }
Referenced by coop(), highest_coop(), highest_preempt(), lowest_coop(), lowest_preempt(), and preempt().
thread_prio() [2/2]
constexpr zpp::thread_prio::thread_prio (int prio) inline explicit constexpr noexcept
Constructor initializing priority to prio.
Parameters
prio The priority value to use for initialization
Definition at line 32 of file thread_prio.hpp.
     : m_prio(prio)
   {
     if (m_prio < -CONFIG_NUM_COOP_PRIORITIES) {
       m_prio = -CONFIG_NUM_COOP_PRIORITIES;
     } else if (m_prio > (CONFIG_NUM_PREEMPT_PRIORITIES - 1)) {
       m_prio = CONFIG_NUM_PREEMPT_PRIORITIES - 1;
     }
     __ASSERT_NO_MSG(m_prio == prio);
   }
Member Function Documentation
coop()
static constexpr thread_prio zpp::thread_prio::coop (int prio) inline static constexpr noexcept
Create a cooperative priority value.
Parameters
prio the value, from 0 to highest_coop
Returns
The priority value
Definition at line 174 of file thread_prio.hpp.
   {
     return thread_prio( lowest_coop().native_value() - prio );
   }
References thread_prio(), lowest_coop(), and native_value().
highest_coop()
static constexpr thread_prio zpp::thread_prio::highest_coop () inline static constexpr noexcept
Get the most prior cooperative priority.
Returns
The most prior cooperative priority
Definition at line 59 of file thread_prio.hpp.
   {
     return thread_prio(-CONFIG_NUM_COOP_PRIORITIES);
   }
References thread_prio().
Referenced by min_coop_numeric().
highest_preempt()
static constexpr thread_prio zpp::thread_prio::highest_preempt () inline static constexpr noexcept
Get the most prior preemptive priority.
Returns
The most prior preemptive priority
Definition at line 79 of file thread_prio.hpp.
   {
     return thread_prio(0);
   }
References thread_prio().
Referenced by min_preempt_numeric(), and preempt().
lowest_coop()
static constexpr thread_prio zpp::thread_prio::lowest_coop () inline static constexpr noexcept
Get the least prior cooperative priority.
Returns
The least prior cooperative priority
Definition at line 69 of file thread_prio.hpp.
   {
     return thread_prio(-1);
   }
References thread_prio().
Referenced by coop(), and max_coop_numeric().
lowest_preempt()
static constexpr thread_prio zpp::thread_prio::lowest_preempt () inline static constexpr noexcept
Get the least prior preemptive priority.
Returns
The least prior preemptive priority
Definition at line 89 of file thread_prio.hpp.
   {
     return thread_prio(CONFIG_NUM_PREEMPT_PRIORITIES - 1);
   }
References thread_prio().
Referenced by max_preempt_numeric(), and preempt().
max_coop_numeric()
static constexpr thread_prio zpp::thread_prio::max_coop_numeric () inline static constexpr noexcept
Get the minium coop numeric value.
The maxium coop numric value is the lowest coop thread priority
Returns
The smallest numeric value
Definition at line 115 of file thread_prio.hpp.
   {
     return lowest_coop();
   }
References lowest_coop().
max_numeric()
static constexpr thread_prio zpp::thread_prio::max_numeric () inline static constexpr noexcept
Get the maxium numeric value.
Returns
The highest numeric value
Definition at line 161 of file thread_prio.hpp.
   {
     return max_preempt_numeric();
   }
References max_preempt_numeric().
max_preempt_numeric()
static constexpr thread_prio zpp::thread_prio::max_preempt_numeric () inline static constexpr noexcept
Get the minium preempt numeric value.
The maxium coop numric value is the lowest thread priority
Returns
The largest numeric value
Definition at line 141 of file thread_prio.hpp.
   {
     return lowest_preempt();
   }
References lowest_preempt().
Referenced by max_numeric().
min_coop_numeric()
static constexpr thread_prio zpp::thread_prio::min_coop_numeric () inline static constexpr noexcept
Get the minium coop numeric value.
The minium coop numric value is the highest thread priority
Returns
The smallest numeric value
Definition at line 102 of file thread_prio.hpp.
   {
     return highest_coop();
   }
References highest_coop().
Referenced by min_numeric().
min_numeric()
static constexpr thread_prio zpp::thread_prio::min_numeric () inline static constexpr noexcept
Get the minium numeric value.
Returns
The smallest numeric value
Definition at line 151 of file thread_prio.hpp.
   {
     return min_coop_numeric();
   }
References min_coop_numeric().
min_preempt_numeric()
static constexpr thread_prio zpp::thread_prio::min_preempt_numeric () inline static constexpr noexcept
Get the minium preempt numeric value.
The minium preempt numric value is the highest preempt thread priority
Returns
The smallest numeric value
Definition at line 128 of file thread_prio.hpp.
   {
     return highest_preempt();
   }
References highest_preempt().
native_value()
constexpr int zpp::thread_prio::native_value () const inline constexpr noexcept
Get the Zephyr native priority value.
Returns
the Zephyr native priority value
Definition at line 49 of file thread_prio.hpp.
   {
     return m_prio;
   }
Referenced by coop(), zpp::thread_attr::native_prio(), and preempt().
preempt()
static constexpr thread_prio zpp::thread_prio::preempt (int prio) inline static constexpr noexcept
Create a preemptive priority value.
Parameters
prio the value, from 0 to highest_preempt
Returns
The priority value
Definition at line 186 of file thread_prio.hpp.
   {
     return (prio >= CONFIG_NUM_PREEMPT_PRIORITIES) ?
       highest_preempt() :
       thread_prio( lowest_preempt().native_value() - prio);
   }
References thread_prio(), highest_preempt(), lowest_preempt(), and native_value().
Referenced by main(), and ZTEST().
The documentation for this class was generated from the following file:
include/zpp/thread_prio.hpp