zpp: zpp::mem_slab_base< T_MemSlab > Class Template Reference
zpp::mem_slab_base< T_MemSlab > Class Template Reference
Allocator that uses k_mem_slab for memory.
#include <mem_slab.hpp>
Public Types
using native_type = struct k_mem_slab
using native_pointer = native_type *
using native_const_pointer = native_type const *
Public Member Functions
void * allocate () noexcept
allocate a memory block, waiting forever
void * try_allocate () noexcept
try allocate a memory block, not waiting
template<class T_Rep , class T_Period >
void * try_allocate_for (const std::chrono::duration< T_Rep, T_Period > &timeout) noexcept
try allocate a memory block waiting with a timeout
void deallocate (void *vp) noexcept
deallocate memory
constexpr auto block_size () const noexcept
the size of the memory blocks
constexpr auto total_block_count () const noexcept
get maximm number of blocks that can be allocated
constexpr auto used_block_count () noexcept
get current number of used blocks
constexpr auto free_block_count () noexcept
get current number of free blocks
auto native_handle () noexcept -> native_pointer
get the native zephyr mem slab handle.
auto native_handle () const noexcept -> native_const_pointer
get the native zephyr mem slab handle.
mem_slab_base (const mem_slab_base &)=delete
mem_slab_base (mem_slab_base &&)=delete
mem_slab_base & operator= (const mem_slab_base &)=delete
mem_slab_base & operator= (mem_slab_base &&)=delete
Protected Member Functions
constexpr mem_slab_base () noexcept
Detailed Description
template<class T_MemSlab>
class zpp::mem_slab_base< T_MemSlab >
Allocator that uses k_mem_slab for memory.
Parameters
T_MemSlab the CRTP type
Definition at line 27 of file mem_slab.hpp.
Member Typedef Documentation
native_const_pointer
template<class T_MemSlab > using zpp::mem_slab_base< T_MemSlab >::native_const_pointer = native_type const *
Definition at line 31 of file mem_slab.hpp.
native_pointer
template<class T_MemSlab > using zpp::mem_slab_base< T_MemSlab >::native_pointer = native_type*
Definition at line 30 of file mem_slab.hpp.
native_type
template<class T_MemSlab > using zpp::mem_slab_base< T_MemSlab >::native_type = struct k_mem_slab
Definition at line 29 of file mem_slab.hpp.
Constructor & Destructor Documentation
mem_slab_base() [1/3]
template<class T_MemSlab > constexpr zpp::mem_slab_base< T_MemSlab >::mem_slab_base () inline constexpr protected noexcept
Definition at line 33 of file mem_slab.hpp.
 {}
mem_slab_base() [2/3]
template<class T_MemSlab > zpp::mem_slab_base< T_MemSlab >::mem_slab_base (const mem_slab_base< T_MemSlab > &) delete
mem_slab_base() [3/3]
template<class T_MemSlab > zpp::mem_slab_base< T_MemSlab >::mem_slab_base (mem_slab_base< T_MemSlab > &&) delete
Member Function Documentation
allocate()
template<class T_MemSlab > void* zpp::mem_slab_base< T_MemSlab >::allocate () inline noexcept
allocate a memory block, waiting forever
Returns
pointer to memory or nullptr on error
Definition at line 41 of file mem_slab.hpp.
   {
     void* vp{nullptr};
     auto rc = k_mem_slab_alloc(native_handle(), &vp, K_FOREVER);
     if (rc == 0) {
       return vp;
     } else {
       return nullptr;
     }
   }
References zpp::mem_slab_base< T_MemSlab >::native_handle().
block_size()
template<class T_MemSlab > constexpr auto zpp::mem_slab_base< T_MemSlab >::block_size () const inline constexpr noexcept
the size of the memory blocks
Returns
the size of the memory blocks in bytes
Definition at line 114 of file mem_slab.hpp.
   {
     return native_handle()->block_size;
   }
References zpp::mem_slab_base< T_MemSlab >::native_handle().
deallocate()
template<class T_MemSlab > void zpp::mem_slab_base< T_MemSlab >::deallocate (void * vp) inline noexcept
deallocate memory
Parameters
vp the pointer to free
Definition at line 102 of file mem_slab.hpp.
   {
     if (vp != nullptr) {
       k_mem_slab_free(native_handle(), &vp);
     }
   }
References zpp::mem_slab_base< T_MemSlab >::native_handle().
free_block_count()
template<class T_MemSlab > constexpr auto zpp::mem_slab_base< T_MemSlab >::free_block_count () inline constexpr noexcept
get current number of free blocks
Returns
the current number of free blocks
Definition at line 144 of file mem_slab.hpp.
   {
     return k_mem_slab_num_free_get(native_handle());
   }
References zpp::mem_slab_base< T_MemSlab >::native_handle().
native_handle() [1/2]
template<class T_MemSlab > auto zpp::mem_slab_base< T_MemSlab >::native_handle () const -> native_const_pointer inline noexcept
get the native zephyr mem slab handle.
Returns
A pointer to the zephyr k_mem_slab.
Definition at line 165 of file mem_slab.hpp.
   {
     return static_cast<const T_MemSlab*>(this)->native_handle();
   }
References zpp::mem_slab_base< T_MemSlab >::native_handle().
native_handle() [2/2]
template<class T_MemSlab > auto zpp::mem_slab_base< T_MemSlab >::native_handle () -> native_pointer inline noexcept
get the native zephyr mem slab handle.
Returns
A pointer to the zephyr k_mem_slab.
Definition at line 155 of file mem_slab.hpp.
   {
     return static_cast<T_MemSlab*>(this)->native_handle();
   }
Referenced by zpp::mem_slab_base< T_MemSlab >::allocate(), zpp::mem_slab_base< T_MemSlab >::block_size(), zpp::mem_slab_base< T_MemSlab >::deallocate(), zpp::mem_slab_base< T_MemSlab >::free_block_count(), zpp::mem_slab_base< T_MemSlab >::native_handle(), zpp::mem_slab_base< T_MemSlab >::total_block_count(), zpp::mem_slab_base< T_MemSlab >::try_allocate(), zpp::mem_slab_base< T_MemSlab >::try_allocate_for(), and zpp::mem_slab_base< T_MemSlab >::used_block_count().
operator=() [1/2]
template<class T_MemSlab > mem_slab_base& zpp::mem_slab_base< T_MemSlab >::operator= (const mem_slab_base< T_MemSlab > &) delete
operator=() [2/2]
template<class T_MemSlab > mem_slab_base& zpp::mem_slab_base< T_MemSlab >::operator= (mem_slab_base< T_MemSlab > &&) delete
total_block_count()
template<class T_MemSlab > constexpr auto zpp::mem_slab_base< T_MemSlab >::total_block_count () const inline constexpr noexcept
get maximm number of blocks that can be allocated
Returns
the maximum number of blocks that can be allocated
Definition at line 124 of file mem_slab.hpp.
   {
     return native_handle()->num_blocks;
   }
References zpp::mem_slab_base< T_MemSlab >::native_handle().
try_allocate()
template<class T_MemSlab > void* zpp::mem_slab_base< T_MemSlab >::try_allocate () inline noexcept
try allocate a memory block, not waiting
Returns
pointer to memory or nullptr on error
Definition at line 60 of file mem_slab.hpp.
   {
     void* vp{nullptr};
     auto rc = k_mem_slab_alloc(native_handle(), &vp, K_NO_WAIT);
     if (rc == 0) {
       return vp;
     } else {
       return nullptr;
     }
   }
References zpp::mem_slab_base< T_MemSlab >::native_handle().
try_allocate_for()
template<class T_MemSlab > template<class T_Rep , class T_Period > void* zpp::mem_slab_base< T_MemSlab >::try_allocate_for (const std::chrono::duration< T_Rep, T_Period > & timeout) inline noexcept
try allocate a memory block waiting with a timeout
Parameters
timeout the time to try
Returns
pointer to memory or nullptr on error
Definition at line 82 of file mem_slab.hpp.
   {
     using namespace std::chrono;
     void* vp{nullptr};
     auto rc = k_mem_slab_alloc(native_handle(), &vp, to_timeout(timeout));
     if (rc == 0) {
       return vp;
     } else {
       return nullptr;
     }
   }
References zpp::mem_slab_base< T_MemSlab >::native_handle(), and zpp::to_timeout().
used_block_count()
template<class T_MemSlab > constexpr auto zpp::mem_slab_base< T_MemSlab >::used_block_count () inline constexpr noexcept
get current number of used blocks
Returns
the current number of used blocks
Definition at line 134 of file mem_slab.hpp.
   {
     return k_mem_slab_num_used_get(native_handle());
   }
References zpp::mem_slab_base< T_MemSlab >::native_handle().
The documentation for this class was generated from the following file:
include/zpp/mem_slab.hpp