zpp: zpp::timer_base Class Reference
zpp::timer_base Class Reference
base class for the timer class
#include <timer.hpp>
Public Member Functions
~timer_base ()
Destructor that stops the timer.
template<class T_Rep1 , class T_Period1 , class T_Rep2 , class T_Period2 >
void start (const std::chrono::duration< T_Rep1, T_Period1 > &duration, const std::chrono::duration< T_Rep2, T_Period2 > &period) noexcept
Start a timer with duration and period.
template<class T_Rep , class T_Period >
void start (const std::chrono::duration< T_Rep, T_Period > &duration) noexcept
Start a single shot timer with duration.
void stop () noexcept
Stop the timer.
auto status () noexcept
get the timer status
auto sync () noexcept
sync with the timer
std::chrono::nanoseconds remaining_time () noexcept
Get remaining time.
auto native_handle () noexcept
Zephyr native handle.
timer_base (const timer_base &)=delete
timer_base (timer_base &&)=delete
timer_base & operator= (const timer_base &)=delete
timer_base & operator= (timer_base &&)=delete
Protected Member Functions
timer_base () noexcept
Detailed Description
base class for the timer class
Definition at line 24 of file timer.hpp.
Constructor & Destructor Documentation
timer_base() [1/3]
zpp::timer_base::timer_base () inline protected noexcept
Definition at line 26 of file timer.hpp.
   {
   }
~timer_base()
zpp::timer_base::~timer_base () inline
Destructor that stops the timer.
Definition at line 33 of file timer.hpp.
   {
     stop();
   }
References stop().
timer_base() [2/3]
zpp::timer_base::timer_base (const timer_base &) delete
timer_base() [3/3]
zpp::timer_base::timer_base (timer_base &&) delete
Member Function Documentation
native_handle()
auto zpp::timer_base::native_handle () inline noexcept
Zephyr native handle.
Returns
pointer to the k_timer
Definition at line 108 of file timer.hpp.
   {
     return &m_timer;
   }
Referenced by zpp::basic_timer< T_ExpireCallback >::basic_timer(), zpp::sync_timer::sync_timer(), and zpp::timer< T_ExpireCallback, T_StopCallback >::timer().
operator=() [1/2]
timer_base& zpp::timer_base::operator= (const timer_base &) delete
operator=() [2/2]
timer_base& zpp::timer_base::operator= (timer_base &&) delete
remaining_time()
std::chrono::nanoseconds zpp::timer_base::remaining_time () inline noexcept
Get remaining time.
Returns
the remaining time
Definition at line 97 of file timer.hpp.
   {
     auto t = k_timer_remaining_ticks(&m_timer);
     return std::chrono::nanoseconds(k_ticks_to_ns_floor64(t));
   }
start() [1/2]
template<class T_Rep , class T_Period > void zpp::timer_base::start (const std::chrono::duration< T_Rep, T_Period > & duration) inline noexcept
Start a single shot timer with duration.
Parameters
duration The timeout
Definition at line 59 of file timer.hpp.
   {
     using namespace std::chrono;
     k_timer_start(&m_timer, to_timeout(duration), K_NO_WAIT);
   }
References zpp::to_timeout().
start() [2/2]
template<class T_Rep1 , class T_Period1 , class T_Rep2 , class T_Period2 > void zpp::timer_base::start (const std::chrono::duration< T_Rep1, T_Period1 > & duration, const std::chrono::duration< T_Rep2, T_Period2 > & period) inline noexcept
Start a timer with duration and period.
Parameters
duration The first time out
period the time of the repeat period
Definition at line 45 of file timer.hpp.
   {
     using namespace std::chrono;
     k_timer_start(&m_timer, to_timeout(duration), to_timeout(period));
   }
References zpp::to_timeout().
status()
auto zpp::timer_base::status () inline noexcept
get the timer status
Returns
the timer status
Definition at line 79 of file timer.hpp.
   {
     return k_timer_status_get(&m_timer);
   }
stop()
void zpp::timer_base::stop () inline noexcept
Stop the timer.
Definition at line 69 of file timer.hpp.
   {
     k_timer_stop(&m_timer);
   }
Referenced by ~timer_base().
sync()
auto zpp::timer_base::sync () inline noexcept
sync with the timer
Definition at line 87 of file timer.hpp.
   {
     return k_timer_status_sync(&m_timer);
   }
The documentation for this class was generated from the following file:
include/zpp/timer.hpp