zpp: zpp::fifo_base< T_BaseFifoType, T_BaseItemType > Class Template Reference
zpp::fifo_base< T_BaseFifoType, T_BaseItemType > Class Template Reference
Fifo CRTP base class.
#include <fifo.hpp>
Public Types
using native_type = struct k_fifo
using native_pointer = native_type *
using native_const_pointer = native_type const *
using item_type = T_BaseItemType
using item_pointer = item_type *
using item_const_pointer = item_type const *
Public Member Functions
constexpr auto native_handle () noexcept -> native_pointer
get the Zephyr native fifo handle
constexpr auto native_handle () const noexcept -> native_const_pointer
get the Zephyr native fifo handle
void cancel_wait () noexcept
force a waiting thread to return with a timeout error
void push_back (item_pointer item) noexcept
push an item on the back of the fifo
item_pointer pop_front () noexcept
pop item from fifo waiting for ever
item_pointer try_pop_front () noexcept
try to pop item from the fifo without waiting
template<class T_Rep , class T_Period >
item_pointer try_pop_front_for (const std::chrono::duration< T_Rep, T_Period > &timeout) noexcept
try to pop item from the fifo waiting a certain amount of time
item_pointer front () noexcept
get item at the front without removing it from the fifo
item_pointer back () noexcept
get item at the back without removing it from the fifo
bool empty () noexcept
check if the fifo is empty
fifo_base (const fifo_base &)=delete
fifo_base (fifo_base &&)=delete
fifo_base & operator= (const fifo_base &)=delete
fifo_base & operator= (fifo_base &&)=delete
Protected Member Functions
fifo_base () noexcept
default constructor, can only be called from derived types
Detailed Description
template<template< typename > typename T_BaseFifoType, typename T_BaseItemType>
class zpp::fifo_base< T_BaseFifoType, T_BaseItemType >
Fifo CRTP base class.
Parameters
T_BaseFifoType the CRTP derived type
T_BaseItemType the item to store in this fifo
Definition at line 27 of file fifo.hpp.
Member Typedef Documentation
item_const_pointer
template<template< typename > typename T_BaseFifoType, typename T_BaseItemType > using zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::item_const_pointer = item_type const *
Definition at line 35 of file fifo.hpp.
item_pointer
template<template< typename > typename T_BaseFifoType, typename T_BaseItemType > using zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::item_pointer = item_type*
Definition at line 34 of file fifo.hpp.
item_type
template<template< typename > typename T_BaseFifoType, typename T_BaseItemType > using zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::item_type = T_BaseItemType
Definition at line 33 of file fifo.hpp.
native_const_pointer
template<template< typename > typename T_BaseFifoType, typename T_BaseItemType > using zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::native_const_pointer = native_type const *
Definition at line 31 of file fifo.hpp.
native_pointer
template<template< typename > typename T_BaseFifoType, typename T_BaseItemType > using zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::native_pointer = native_type *
Definition at line 30 of file fifo.hpp.
native_type
template<template< typename > typename T_BaseFifoType, typename T_BaseItemType > using zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::native_type = struct k_fifo
Definition at line 29 of file fifo.hpp.
Constructor & Destructor Documentation
fifo_base() [1/3]
template<template< typename > typename T_BaseFifoType, typename T_BaseItemType > zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::fifo_base () inline protected noexcept
default constructor, can only be called from derived types
Definition at line 40 of file fifo.hpp.
   {
     static_assert(std::is_standard_layout_v<item_type>);
     static_assert(std::is_same_v<void*, decltype(item_type::fifo_reserved)>);
     static_assert(offsetof(item_type, fifo_reserved) == 0);
   }
fifo_base() [2/3]
template<template< typename > typename T_BaseFifoType, typename T_BaseItemType > zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::fifo_base (const fifo_base< T_BaseFifoType, T_BaseItemType > &) delete
fifo_base() [3/3]
template<template< typename > typename T_BaseFifoType, typename T_BaseItemType > zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::fifo_base (fifo_base< T_BaseFifoType, T_BaseItemType > &&) delete
Member Function Documentation
back()
template<template< typename > typename T_BaseFifoType, typename T_BaseItemType > item_pointer zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::back () inline noexcept
get item at the back without removing it from the fifo
Returns
the item or nullptr on error/timeout
Definition at line 144 of file fifo.hpp.
   {
     return static_cast<item_pointer>(
       k_fifo_peek_tail(native_handle()));
   }
References zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::native_handle().
cancel_wait()
template<template< typename > typename T_BaseFifoType, typename T_BaseItemType > void zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::cancel_wait () inline noexcept
force a waiting thread to return with a timeout error
Definition at line 70 of file fifo.hpp.
   {
     k_fifo_cancel_wait(native_handle());
   }
References zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::native_handle().
empty()
template<template< typename > typename T_BaseFifoType, typename T_BaseItemType > bool zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::empty () inline noexcept
check if the fifo is empty
Returns
true if the fifo is empty
Definition at line 155 of file fifo.hpp.
   {
     auto res  = k_fifo_is_empty(native_handle());
     if (res == 0) {
       return false;
     } else {
       return true;
     }
   }
References zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::native_handle().
front()
template<template< typename > typename T_BaseFifoType, typename T_BaseItemType > item_pointer zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::front () inline noexcept
get item at the front without removing it from the fifo
Returns
the item or nullptr on error/timeout
Definition at line 133 of file fifo.hpp.
   {
     return static_cast<item_pointer>(
       k_fifo_peek_head(native_handle()));
   }
References zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::native_handle().
native_handle() [1/2]
template<template< typename > typename T_BaseFifoType, typename T_BaseItemType > constexpr auto zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::native_handle () const -> native_const_pointer inline constexpr noexcept
get the Zephyr native fifo handle
Returns
pointer to a k_fifo
Definition at line 62 of file fifo.hpp.
   {
     return static_cast<const T_BaseFifoType<item_type>*>(this)->native_handle();
   }
References zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::native_handle().
native_handle() [2/2]
template<template< typename > typename T_BaseFifoType, typename T_BaseItemType > constexpr auto zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::native_handle () -> native_pointer inline constexpr noexcept
get the Zephyr native fifo handle
Returns
pointer to a k_fifo
Definition at line 52 of file fifo.hpp.
   {
     return static_cast<T_BaseFifoType<item_type>*>(this)->native_handle();
   }
Referenced by zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::back(), zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::cancel_wait(), zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::empty(), zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::front(), zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::native_handle(), zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::pop_front(), zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::push_back(), zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::try_pop_front(), and zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::try_pop_front_for().
operator=() [1/2]
template<template< typename > typename T_BaseFifoType, typename T_BaseItemType > fifo_base& zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::operator= (const fifo_base< T_BaseFifoType, T_BaseItemType > &) delete
operator=() [2/2]
template<template< typename > typename T_BaseFifoType, typename T_BaseItemType > fifo_base& zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::operator= (fifo_base< T_BaseFifoType, T_BaseItemType > &&) delete
pop_front()
template<template< typename > typename T_BaseFifoType, typename T_BaseItemType > item_pointer zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::pop_front () inline noexcept
pop item from fifo waiting for ever
Returns
the item or nullptr on error
Definition at line 91 of file fifo.hpp.
   {
     return static_cast<item_pointer>(
       k_fifo_get(native_handle(), K_FOREVER));
   }
References zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::native_handle().
push_back()
template<template< typename > typename T_BaseFifoType, typename T_BaseItemType > void zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::push_back (item_pointer item) inline noexcept
push an item on the back of the fifo
Parameters
item Pointer to a item, the fifo does not take ownership
Definition at line 80 of file fifo.hpp.
   {
     k_fifo_put(native_handle(), item);
   }
References zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::native_handle().
try_pop_front()
template<template< typename > typename T_BaseFifoType, typename T_BaseItemType > item_pointer zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::try_pop_front () inline noexcept
try to pop item from the fifo without waiting
Returns
the item or nullptr on error/timeout
Definition at line 103 of file fifo.hpp.
   {
     return static_cast<item_pointer>(
       k_fifo_get(native_handle(), K_NO_WAIT));
   }
References zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::native_handle().
try_pop_front_for()
template<template< typename > typename T_BaseFifoType, typename T_BaseItemType > template<class T_Rep , class T_Period > item_pointer zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::try_pop_front_for (const std::chrono::duration< T_Rep, T_Period > & timeout) inline noexcept
try to pop item from the fifo waiting a certain amount of time
Parameters
timeout The timeout before returning
Returns
the item or nullptr on error/timeout
Definition at line 118 of file fifo.hpp.
   {
     using namespace std::chrono;
     return static_cast<item_pointer>(
       k_fifo_get(native_handle(),
       duration_cast<milliseconds>(timeout).count()));
   }
References zpp::fifo_base< T_BaseFifoType, T_BaseItemType >::native_handle().
The documentation for this class was generated from the following file:
include/zpp/fifo.hpp