zpp: zpp::mutex_base< T_Mutex > Class Template Reference
zpp::mutex_base< T_Mutex > Class Template Reference
A recursive mutex CRTP base class.
#include <mutex.hpp>
Public Types
using native_type = struct k_mutex
using native_pointer = native_type *
using native_const_pointer = native_type const *
Public Member Functions
auto lock () noexcept
Lock the mutex. Wait forever until it is locked.
auto try_lock () noexcept
Try locking the mutex without waiting.
template<class T_Rep , class T_Period >
auto try_lock_for (const std::chrono::duration< T_Rep, T_Period > &timeout) noexcept
Try locking the mutex with a timeout.
auto unlock () noexcept
Unlock the mutex.
auto native_handle () noexcept -> native_pointer
get the native zephyr mutex handle.
auto native_handle () const noexcept -> native_const_pointer
get the native zephyr mutex handle.
mutex_base (const mutex_base &)=delete
mutex_base (mutex_base &&)=delete
mutex_base & operator= (const mutex_base &)=delete
mutex_base & operator= (mutex_base &&)=delete
Protected Member Functions
constexpr mutex_base () noexcept
Protected default constructor so only derived objects can be created.
Detailed Description
template<typename T_Mutex>
class zpp::mutex_base< T_Mutex >
A recursive mutex CRTP base class.
Definition at line 24 of file mutex.hpp.
Member Typedef Documentation
native_const_pointer
template<typename T_Mutex > using zpp::mutex_base< T_Mutex >::native_const_pointer = native_type const *
Definition at line 29 of file mutex.hpp.
native_pointer
template<typename T_Mutex > using zpp::mutex_base< T_Mutex >::native_pointer = native_type*
Definition at line 28 of file mutex.hpp.
native_type
template<typename T_Mutex > using zpp::mutex_base< T_Mutex >::native_type = struct k_mutex
Definition at line 27 of file mutex.hpp.
Constructor & Destructor Documentation
mutex_base() [1/3]
template<typename T_Mutex > constexpr zpp::mutex_base< T_Mutex >::mutex_base () inline constexpr protected noexcept
Protected default constructor so only derived objects can be created.
Definition at line 34 of file mutex.hpp.
   {
   }
mutex_base() [2/3]
template<typename T_Mutex > zpp::mutex_base< T_Mutex >::mutex_base (const mutex_base< T_Mutex > &) delete
mutex_base() [3/3]
template<typename T_Mutex > zpp::mutex_base< T_Mutex >::mutex_base (mutex_base< T_Mutex > &&) delete
Member Function Documentation
lock()
template<typename T_Mutex > auto zpp::mutex_base< T_Mutex >::lock () inline noexcept
Lock the mutex. Wait forever until it is locked.
Returns
true if successfully locked.
Definition at line 44 of file mutex.hpp.
   {
     result<void, error_code> res;
     auto rc = k_mutex_lock(native_handle(), K_FOREVER);
     if (rc == 0) {
       res.assign_value();
     } else {
       res.assign_error(to_error_code(-rc));
     }
     return res;
   }
References zpp::result< T_Ok, T_Error >::assign_error(), zpp::result< T_Ok, T_Error >::assign_value(), zpp::mutex_base< T_Mutex >::native_handle(), and zpp::to_error_code().
native_handle() [1/2]
template<typename T_Mutex > auto zpp::mutex_base< T_Mutex >::native_handle () const -> native_const_pointer inline noexcept
get the native zephyr mutex handle.
Returns
A pointer to the zephyr k_mutex.
Definition at line 136 of file mutex.hpp.
   {
     return static_cast<const T_Mutex*>(this)->native_handle();
   }
References zpp::mutex_base< T_Mutex >::native_handle().
native_handle() [2/2]
template<typename T_Mutex > auto zpp::mutex_base< T_Mutex >::native_handle () -> native_pointer inline noexcept
get the native zephyr mutex handle.
Returns
A pointer to the zephyr k_mutex.
Definition at line 126 of file mutex.hpp.
   {
     return static_cast<T_Mutex*>(this)->native_handle();
   }
Referenced by zpp::mutex_base< T_Mutex >::lock(), zpp::mutex_base< T_Mutex >::native_handle(), zpp::mutex_base< T_Mutex >::try_lock(), zpp::mutex_base< T_Mutex >::try_lock_for(), and zpp::mutex_base< T_Mutex >::unlock().
operator=() [1/2]
template<typename T_Mutex > mutex_base& zpp::mutex_base< T_Mutex >::operator= (const mutex_base< T_Mutex > &) delete
operator=() [2/2]
template<typename T_Mutex > mutex_base& zpp::mutex_base< T_Mutex >::operator= (mutex_base< T_Mutex > &&) delete
try_lock()
template<typename T_Mutex > auto zpp::mutex_base< T_Mutex >::try_lock () inline noexcept
Try locking the mutex without waiting.
Returns
true if successfully locked.
Definition at line 63 of file mutex.hpp.
   {
     result<void, error_code> res;
     auto rc = k_mutex_lock(native_handle(), K_NO_WAIT);
     if (rc == 0) {
       res.assign_value();
     } else {
       res.assign_error(to_error_code(-rc));
     }
     return res;
   }
References zpp::result< T_Ok, T_Error >::assign_error(), zpp::result< T_Ok, T_Error >::assign_value(), zpp::mutex_base< T_Mutex >::native_handle(), and zpp::to_error_code().
try_lock_for()
template<typename T_Mutex > template<class T_Rep , class T_Period > auto zpp::mutex_base< T_Mutex >::try_lock_for (const std::chrono::duration< T_Rep, T_Period > & timeout) inline noexcept
Try locking the mutex with a timeout.
Parameters
timeout The time to wait before returning
Returns
true if successfully locked.
Definition at line 86 of file mutex.hpp.
   {
     using namespace std::chrono;
     result<void, error_code> res;
     auto rc = k_mutex_lock(native_handle(), to_timeout(timeout));
     if (rc == 0) {
       res.assign_value();
     } else {
       res.assign_error(to_error_code(-rc));
     }
     return res;
   }
References zpp::result< T_Ok, T_Error >::assign_error(), zpp::result< T_Ok, T_Error >::assign_value(), zpp::mutex_base< T_Mutex >::native_handle(), zpp::to_error_code(), and zpp::to_timeout().
unlock()
template<typename T_Mutex > auto zpp::mutex_base< T_Mutex >::unlock () inline noexcept
Unlock the mutex.
Returns
true on success
Definition at line 107 of file mutex.hpp.
   {
     result<void, error_code> res;
     auto rc = k_mutex_unlock(native_handle());
     if (rc == 0) {
       res.assign_value();
     } else {
       res.assign_error(to_error_code(-rc));
     }
     return res;
   }
References zpp::result< T_Ok, T_Error >::assign_error(), zpp::result< T_Ok, T_Error >::assign_value(), zpp::mutex_base< T_Mutex >::native_handle(), and zpp::to_error_code().
The documentation for this class was generated from the following file:
include/zpp/mutex.hpp