zpp: zpp::atomic_var Class Reference
zpp::atomic_var Class Reference
class wrapping an atomic_var_t
#include <atomic_var.hpp>
Public Types
using value_type = atomic_val_t
the type used to store the value
Public Member Functions
constexpr atomic_var () noexcept=default
default constructor that sets the value to 0
atomic_var (value_type v) noexcept
constructor that sets the value to v
atomic_var (const atomic_var &rhs) noexcept
copy constructor
atomic_var & operator= (const atomic_var &rhs) noexcept
copy operator
constexpr size_t bit_count () const noexcept
the size in bits of value_type
bool cas (value_type old_val, value_type new_val) noexcept
Atomic compare-and-set.
value_type fetch_add (value_type val) noexcept
Atomic addition.
value_type fetch_sub (value_type val) noexcept
Atomic substraction.
value_type fetch_or (value_type val) noexcept
Atomic bitwise OR.
value_type fetch_xor (value_type val) noexcept
Atomic bitwise XOR.
value_type fetch_and (value_type val) noexcept
Atomic bitwise AND.
value_type fetch_nand (value_type val) noexcept
Atomic bitwise NAND.
value_type fetch_inc () noexcept
Atomic increment.
value_type fetch_dec () noexcept
Atomic decrement.
value_type load () const noexcept
Atomically loads and returns the current value of the atomic variable.
value_type store (value_type val) noexcept
Atomically replace current value of the atomic variable.
value_type clear () noexcept
Atomically clear the atomic variable.
bool load (size_t bit) const noexcept
atomically get a bit from the bitset
void store (size_t bit, bool val) noexcept
atomically set a bit a value
void set (size_t bit) noexcept
atomically set a bit to true/1
void clear (size_t bit) noexcept
atomically set a bit to false/0
bool fetch_and_clear (size_t bit) noexcept
atomically clear a bit while returning the previous value.
bool fetch_and_set (size_t bit) noexcept
atomically set a bit while returning the previous value.
operator value_type () const noexcept
Atomically loads and returns the current value of the atomic variable.
value_type operator= (value_type val) noexcept
Atomically replace current value of the atomic variable.
value_type operator++ () noexcept
Perform atomic pre-increment.
value_type operator++ (int) noexcept
Perform atomic post-increment.
value_type operator-- () noexcept
Perform atomic pre-decrement.
value_type operator-- (int) noexcept
Perform atomic post-decrement.
value_type operator+= (value_type val) noexcept
Perform atomic addition.
value_type operator-= (value_type val) noexcept
Perform atomic substraction.
value_type operator&= (value_type val) noexcept
Perform atomic bitwise AND.
value_type operator|= (value_type val) noexcept
Perform atomic bitwise OR.
value_type operator^= (value_type val) noexcept
Perform atomic bitwise XOR.
Detailed Description
class wrapping an atomic_var_t
Definition at line 20 of file atomic_var.hpp.
Member Typedef Documentation
value_type
using zpp::atomic_var::value_type = atomic_val_t
the type used to store the value
Definition at line 25 of file atomic_var.hpp.
Constructor & Destructor Documentation
atomic_var() [1/3]
constexpr zpp::atomic_var::atomic_var () constexpr default noexcept
default constructor that sets the value to 0
atomic_var() [2/3]
zpp::atomic_var::atomic_var (value_type v) inline explicit noexcept
constructor that sets the value to v
Parameters
v the value to initialize the atomic_var with
Definition at line 37 of file atomic_var.hpp.
   {
     store(v);
   }
References store().
atomic_var() [3/3]
zpp::atomic_var::atomic_var (const atomic_var & rhs) inline noexcept
copy constructor
Parameters
rhs the value to initialize the atomic_var with
Definition at line 47 of file atomic_var.hpp.
   {
     store(rhs.load());
   }
References store().
Member Function Documentation
bit_count()
constexpr size_t zpp::atomic_var::bit_count () const inline constexpr noexcept
the size in bits of value_type
Returns
the size of value_type in bits
Definition at line 70 of file atomic_var.hpp.
   {
     return sizeof(value_type) * 8;
   }
cas()
bool zpp::atomic_var::cas (value_type old_val, value_type new_val) inline noexcept
Atomic compare-and-set.
This routine performs an atomic compare-and-set. If the current value equals old_val, the value is set to new_val. If the current value does not equal old_val, the value is unchanged.
Parameters
old_val Original value to compare against.
new_val New value to store.
Returns
true if new_val is written, false otherwise.
Definition at line 88 of file atomic_var.hpp.
   {
     return atomic_cas(&m_var, old_val, new_val);
   }
clear() [1/2]
value_type zpp::atomic_var::clear () inline noexcept
Atomically clear the atomic variable.
Returns
The value immediately preceding the effect or this function.
Definition at line 237 of file atomic_var.hpp.
   {
     return atomic_clear(&m_var);
   }
clear() [2/2]
void zpp::atomic_var::clear (size_t bit) inline noexcept
atomically set a bit to false/0
Parameters
bit the index of the bit to set
Definition at line 283 of file atomic_var.hpp.
   {
     __ASSERT_NO_MSG(bit < (sizeof(value_type) * 8));
     atomic_clear_bit(&m_var, bit);
   }
fetch_add()
value_type zpp::atomic_var::fetch_add (value_type val) inline noexcept
Atomic addition.
Atomically replace the current value with the result of the aritmetic addition of the value and val.
Parameters
val The other argument of the arithmetic addition.
Returns
The value immediately preceding the effect or this function.
Definition at line 103 of file atomic_var.hpp.
   {
     return atomic_add(&m_var, val);
   }
Referenced by operator++(), and operator+=().
fetch_and()
value_type zpp::atomic_var::fetch_and (value_type val) inline noexcept
Atomic bitwise AND.
Atomically replace the current value with the result of the bitwise AND of the value and val.
Parameters
val The other argument of the bitwise AND.
Returns
The value immediately preceding the effect or this function.
Definition at line 163 of file atomic_var.hpp.
   {
     return atomic_and(&m_var, val);
   }
Referenced by operator&=().
fetch_and_clear()
bool zpp::atomic_var::fetch_and_clear (size_t bit) inline noexcept
atomically clear a bit while returning the previous value.
Parameters
bit the index of the bit to set
Returns
the bit value before it was cleared
Definition at line 296 of file atomic_var.hpp.
   {
     __ASSERT_NO_MSG(bit < (sizeof(value_type) * 8));
     return atomic_test_and_clear_bit(&m_var, bit);
   }
fetch_and_set()
bool zpp::atomic_var::fetch_and_set (size_t bit) inline noexcept
atomically set a bit while returning the previous value.
Parameters
bit the index of the bit to set
Returns
the bit value before it was set
Definition at line 309 of file atomic_var.hpp.
   {
     __ASSERT_NO_MSG(bit < (sizeof(value_type) * 8));
     return atomic_test_and_set_bit(&m_var, bit);
   }
fetch_dec()
value_type zpp::atomic_var::fetch_dec () inline noexcept
Atomic decrement.
Atomically replace the current value with the result of the aritmetic substraction of the value and 1.
Returns
The value immediately preceding the effect or this function.
Definition at line 204 of file atomic_var.hpp.
   {
     return atomic_dec(&m_var);
   }
fetch_inc()
value_type zpp::atomic_var::fetch_inc () inline noexcept
Atomic increment.
Atomically replace the current value with the result of the aritmetic addition of the value and 1.
Returns
The value immediately preceding the effect or this function.
Definition at line 191 of file atomic_var.hpp.
   {
     return atomic_inc(&m_var);
   }
fetch_nand()
value_type zpp::atomic_var::fetch_nand (value_type val) inline noexcept
Atomic bitwise NAND.
Atomically replace the current value with the result of the bitwise NAND of the value and val.
Parameters
val The other argument of the bitwise NAND.
Returns
The value immediately preceding the effect or this function.
Definition at line 178 of file atomic_var.hpp.
   {
     return atomic_nand(&m_var, val);
   }
fetch_or()
value_type zpp::atomic_var::fetch_or (value_type val) inline noexcept
Atomic bitwise OR.
Atomically replace the current value with the result of the bitwise OR of the value and val.
Parameters
val The other argument of the bitwise OR.
Returns
The value immediately preceding the effect or this function.
Definition at line 133 of file atomic_var.hpp.
   {
     return atomic_or(&m_var, val);
   }
Referenced by operator|=().
fetch_sub()
value_type zpp::atomic_var::fetch_sub (value_type val) inline noexcept
Atomic substraction.
Atomically replace the current value with the result of the aritmetic substraction of the value and val.
Parameters
val The other argument of the arithmetic substraction.
Returns
The value immediately preceding the effect or this function.
Definition at line 118 of file atomic_var.hpp.
   {
     return atomic_sub(&m_var, val);
   }
Referenced by operator--(), and operator-=().
fetch_xor()
value_type zpp::atomic_var::fetch_xor (value_type val) inline noexcept
Atomic bitwise XOR.
Atomically replace the current value with the result of the bitwise XOR of the value and val.
Parameters
val The other argument of the bitwise XOR.
Returns
The value immediately preceding the effect or this function.
Definition at line 148 of file atomic_var.hpp.
   {
     return atomic_xor(&m_var, val);
   }
Referenced by operator^=().
load() [1/2]
value_type zpp::atomic_var::load () const inline noexcept
Atomically loads and returns the current value of the atomic variable.
Returns
The current value of the atomic variable.
Definition at line 215 of file atomic_var.hpp.
   {
     return atomic_get(&m_var);
   }
Referenced by operator value_type().
load() [2/2]
bool zpp::atomic_var::load (size_t bit) const inline noexcept
atomically get a bit from the bitset
Parameters
bit the index of the bit to return
Returns
the requested bit value
Definition at line 249 of file atomic_var.hpp.
   {
     __ASSERT_NO_MSG(bit < (sizeof(value_type) * 8));
     return atomic_test_bit(&m_var, bit);
   }
operator value_type()
zpp::atomic_var::operator value_type () const inline noexcept
Atomically loads and returns the current value of the atomic variable.
Returns
The current value of the atomic variable.
Definition at line 321 of file atomic_var.hpp.
   {
     return load();
   }
References load().
operator&=()
value_type zpp::atomic_var::operator&= (value_type val) inline noexcept
Perform atomic bitwise AND.
Perform atomic bitwise AND, equivalent to fetch_and(val) & val
Parameters
val The argument for the arithmetic operation
Returns
The value immediately after the effect or this function.
Definition at line 423 of file atomic_var.hpp.
   {
     return fetch_and(val) & val;
   }
References fetch_and().
operator++() [1/2]
value_type zpp::atomic_var::operator++ () inline noexcept
Perform atomic pre-increment.
Perform atomic pre-increment, equivalent to fetch_add(1) + 1
Returns
The value immediately after the effect or this function.
Definition at line 345 of file atomic_var.hpp.
   {
     return fetch_add(1) + 1;
   }
References fetch_add().
operator++() [2/2]
value_type zpp::atomic_var::operator++ (int) inline noexcept
Perform atomic post-increment.
Perform atomic pre-increment, equivalent to fetch_add(1)
Returns
The value immediately before the effect or this function.
Definition at line 357 of file atomic_var.hpp.
   {
     return fetch_add(1);
   }
References fetch_add().
operator+=()
value_type zpp::atomic_var::operator+= (value_type val) inline noexcept
Perform atomic addition.
Perform atomic addition, equivalent to fetch_add(val) + val
Parameters
val The argument for the arithmetic operation
Returns
The value immediately after the effect or this function.
Definition at line 395 of file atomic_var.hpp.
   {
     return fetch_add(val) + val;
   }
References fetch_add().
operator--() [1/2]
value_type zpp::atomic_var::operator-- () inline noexcept
Perform atomic pre-decrement.
Perform atomic pre-decrement, equivalent to fetch_sub(1) - 1
Returns
The value immediately after the effect or this function.
Definition at line 369 of file atomic_var.hpp.
   {
     return fetch_sub(1) - 1;
   }
References fetch_sub().
operator--() [2/2]
value_type zpp::atomic_var::operator-- (int) inline noexcept
Perform atomic post-decrement.
Perform atomic pre-decrement, equivalent to fetch_sub(1)
Returns
The value immediately before the effect or this function.
Definition at line 381 of file atomic_var.hpp.
   {
     return fetch_sub(1);
   }
References fetch_sub().
operator-=()
value_type zpp::atomic_var::operator-= (value_type val) inline noexcept
Perform atomic substraction.
Perform atomic addition, equivalent to fetch_sub(val) - val
Parameters
val The argument for the arithmetic operation
Returns
The value immediately after the effect or this function.
Definition at line 409 of file atomic_var.hpp.
   {
     return fetch_sub(val) - val;
   }
References fetch_sub().
operator=() [1/2]
atomic_var& zpp::atomic_var::operator= (const atomic_var & rhs) inline noexcept
copy operator
Parameters
rhs the value to initialize the atomic_var with
Returns
*this
Definition at line 59 of file atomic_var.hpp.
   {
     store(rhs.load());
     return *this;
   }
References store().
operator=() [2/2]
value_type zpp::atomic_var::operator= (value_type val) inline noexcept
Atomically replace current value of the atomic variable.
Parameters
val The value to store in the atomic variable
Returns
The value immediately preceding the effect or this function.
Definition at line 333 of file atomic_var.hpp.
   {
     return store(val);
   }
References store().
operator^=()
value_type zpp::atomic_var::operator^= (value_type val) inline noexcept
Perform atomic bitwise XOR.
Perform atomic bitwise XOR, equivalent to fetch_xor(val) ^ val
Parameters
val The argument for the arithmetic operation
Returns
The value immediately after the effect or this function.
Definition at line 451 of file atomic_var.hpp.
   {
     return fetch_xor(val) ^ val;
   }
References fetch_xor().
operator|=()
value_type zpp::atomic_var::operator|= (value_type val) inline noexcept
Perform atomic bitwise OR.
Perform atomic bitwise OR, equivalent to fetch_or(val) | val
Parameters
val The argument for the arithmetic operation
Returns
The value immediately after the effect or this function.
Definition at line 437 of file atomic_var.hpp.
   {
     return fetch_or(val) | val;
   }
References fetch_or().
set()
void zpp::atomic_var::set (size_t bit) inline noexcept
atomically set a bit to true/1
Parameters
bit the index of the bit to set
Definition at line 272 of file atomic_var.hpp.
   {
     __ASSERT_NO_MSG(bit < (sizeof(value_type) * 8));
     atomic_set_bit(&m_var, bit);
   }
store() [1/2]
void zpp::atomic_var::store (size_t bit, bool val) inline noexcept
atomically set a bit a value
Parameters
bit the index of the bit to set
val the value the bit should be set to
Definition at line 261 of file atomic_var.hpp.
   {
     __ASSERT_NO_MSG(bit < (sizeof(value_type) * 8));
     atomic_set_bit_to(&m_var, bit, val);
   }
store() [2/2]
value_type zpp::atomic_var::store (value_type val) inline noexcept
Atomically replace current value of the atomic variable.
Parameters
val The value to store in the atomic variable
Returns
The value immediately preceding the effect or this function.
Definition at line 227 of file atomic_var.hpp.
   {
     return atomic_set(&m_var, val);
   }
Referenced by atomic_var(), and operator=().
The documentation for this class was generated from the following file:
include/zpp/atomic_var.hpp