zpp: zpp::thread_attr Class Reference
zpp::thread_attr Class Reference
Thread creation attributes.
#include <thread_attr.hpp>
Public Member Functions
thread_attr (const thread_attr &) noexcept=default
thread_attr (thread_attr &&) noexcept=default
thread_attr & operator= (const thread_attr &) noexcept=default
thread_attr & operator= (thread_attr &&) noexcept=default
template<class ... T_Args>
constexpr thread_attr (T_Args &&... args) noexcept
Constructor taking a variable number of attributes.
template<class T_FirstArg , class ... T_Args>
constexpr void set (T_FirstArg &&first, T_Args &&... rest) noexcept
constexpr void set () const noexcept
constexpr void set (thread_prio prio) noexcept
Set the thread priority.
template<class T_Rep , class T_Period >
constexpr void set (const thread_start_delay< T_Rep, T_Period > &delay) noexcept
Set the thread start delay.
constexpr void set (thread_suspend v) noexcept
Set the thread start suspended flag.
constexpr void set (thread_essential v) noexcept
Set the thread essential flag.
constexpr void set (thread_user v) noexcept
Set the thread user flag.
constexpr void set (thread_inherit_perms v) noexcept
Set the thread inherit permisions flag.
constexpr void set (thread_fp_regs v) noexcept
Set the thread FP regs flag.
constexpr void set (thread_sse_regs v) noexcept
Set the thread SSE regs flag.
constexpr auto native_delay () const noexcept
get the Zephyr native delay value
constexpr auto native_prio () const noexcept
get the Zephyr native priority value
constexpr auto native_options () const noexcept
get the Zephyr native options value
Detailed Description
Thread creation attributes.
Definition at line 35 of file thread_attr.hpp.
Constructor & Destructor Documentation
thread_attr() [1/3]
zpp::thread_attr::thread_attr (const thread_attr &) default noexcept
thread_attr() [2/3]
zpp::thread_attr::thread_attr (thread_attr &&) default noexcept
thread_attr() [3/3]
template<class ... T_Args> constexpr zpp::thread_attr::thread_attr (T_Args &&... args) inline explicit constexpr noexcept
Constructor taking a variable number of attributes.
Contructor that initializes the thread creation attributes based on the args arguments being passed. The order of the arguments does not matter. Arguments must be of a Type that has a coresponding set(Type) function.
Parameters
args The attributes to set.
Definition at line 53 of file thread_attr.hpp.
   {
     set(std::forward<T_Args>(args)...);
   }
References set().
Member Function Documentation
native_delay()
constexpr auto zpp::thread_attr::native_delay () const inline constexpr noexcept
get the Zephyr native delay value
Returns
The native delay value
Definition at line 194 of file thread_attr.hpp.
   {
     return m_delay;
   }
native_options()
constexpr auto zpp::thread_attr::native_options () const inline constexpr noexcept
get the Zephyr native options value
Returns
The native options value
Definition at line 214 of file thread_attr.hpp.
   {
     return m_options;
   }
native_prio()
constexpr auto zpp::thread_attr::native_prio () const inline constexpr noexcept
get the Zephyr native priority value
Returns
The native priority value
Definition at line 204 of file thread_attr.hpp.
   {
     return m_prio.native_value();
   }
References zpp::thread_prio::native_value().
operator=() [1/2]
thread_attr& zpp::thread_attr::operator= (const thread_attr &) default noexcept
operator=() [2/2]
thread_attr& zpp::thread_attr::operator= (thread_attr &&) default noexcept
set() [1/10]
constexpr void zpp::thread_attr::set () const inline constexpr noexcept
Definition at line 65 of file thread_attr.hpp.
   {
   }
Referenced by thread_attr(), and set().
set() [2/10]
template<class T_Rep , class T_Period > constexpr void zpp::thread_attr::set (const thread_start_delay< T_Rep, T_Period > & delay) inline constexpr noexcept
Set the thread start delay.
Parameters
delay The thread start delay
Definition at line 86 of file thread_attr.hpp.
   {
     using namespace std::chrono;
     //auto ms = duration_cast<milliseconds>(delay.t);
     if (delay.t <= decltype(delay.t)::zero()) {
       m_delay = K_NO_WAIT;
     } else {
       m_delay = to_tick(delay.t);
     }
   }
References zpp::to_tick().
set() [3/10]
template<class T_FirstArg , class ... T_Args> constexpr void zpp::thread_attr::set (T_FirstArg && first, T_Args &&... rest) inline constexpr noexcept
Definition at line 59 of file thread_attr.hpp.
   {
     set(std::forward<T_FirstArg>(first));
     set(std::forward<T_Args>(rest)...);
   }
References set().
Referenced by ZTEST().
set() [4/10]
constexpr void zpp::thread_attr::set (thread_essential v) inline constexpr noexcept
Set the thread essential flag.
Parameters
v The thread essential flag
Definition at line 120 of file thread_attr.hpp.
   {
     if (v == thread_essential::yes) {
       m_options |= K_ESSENTIAL;
     } else {
       m_options &= ~K_ESSENTIAL;
     }
   }
References zpp::yes.
set() [5/10]
constexpr void zpp::thread_attr::set (thread_fp_regs v) inline constexpr noexcept
Set the thread FP regs flag.
Parameters
v The thread FP regs flag
Definition at line 162 of file thread_attr.hpp.
   {
 #ifdef K_FP_REGS
     if (v == thread_fp_regs::yes) {
       m_options |= K_FP_REGS;
     } else {
       m_options &= ~K_FP_REGS;
     }
 #endif
   }
References zpp::yes.
set() [6/10]
constexpr void zpp::thread_attr::set (thread_inherit_perms v) inline constexpr noexcept
Set the thread inherit permisions flag.
Parameters
v The thread inherit permissions flag
Definition at line 148 of file thread_attr.hpp.
   {
     if (v == thread_inherit_perms::yes) {
       m_options |= K_INHERIT_PERMS;
     } else {
       m_options &= ~K_INHERIT_PERMS;
     }
   }
References zpp::yes.
set() [7/10]
constexpr void zpp::thread_attr::set (thread_prio prio) inline constexpr noexcept
Set the thread priority.
Parameters
prio The thread priority
Definition at line 74 of file thread_attr.hpp.
   {
     m_prio = prio;
   }
set() [8/10]
constexpr void zpp::thread_attr::set (thread_sse_regs v) inline constexpr noexcept
Set the thread SSE regs flag.
Parameters
v The thread SSE regs flag
Definition at line 178 of file thread_attr.hpp.
   {
 #ifdef K_SSE_REGS
     if (v == thread_sse_regs::yes) {
       m_options |= K_SSE_REGS;
     } else {
       m_options &= ~K_SSE_REGS;
     }
 #endif
   }
References zpp::yes.
set() [9/10]
constexpr void zpp::thread_attr::set (thread_suspend v) inline constexpr noexcept
Set the thread start suspended flag.
Parameters
v The thread start suspended flag
Definition at line 104 of file thread_attr.hpp.
   {
     if (v == thread_suspend::yes) {
       m_delay = K_FOREVER;
     } else {
       if (K_TIMEOUT_EQ(m_delay, K_FOREVER)) {
         m_delay = K_NO_WAIT;
       }
     }
   }
References zpp::yes.
set() [10/10]
constexpr void zpp::thread_attr::set (thread_user v) inline constexpr noexcept
Set the thread user flag.
Parameters
v The thread user flag
Definition at line 134 of file thread_attr.hpp.
   {
     if (v == thread_user::yes) {
       m_options |= K_USER;
     } else {
       m_options &= ~K_USER;
     }
   }
References zpp::yes.
The documentation for this class was generated from the following file:
include/zpp/thread_attr.hpp