zpp: zpp::poll_event_set< T_Size > Class Template Reference
zpp::poll_event_set< T_Size > Class Template Reference
A set of poll events.
#include <poll_event_set.hpp>
Public Member Functions
auto begin () noexcept
auto end () noexcept
poll_event_set () noexcept
default constructor
template<class... T_Args>
poll_event_set (T_Args &&... t) noexcept
constructor that takes arguments for initialization
auto operator[] (size_t idx) noexcept
access an element of the set
auto poll () noexcept
poll events waiting for ever
auto try_poll () noexcept
try poll events without waiting
template<class T_Rep , class T_Period >
auto try_poll_for (const std::chrono::duration< T_Rep, T_Period > &timeout) noexcept
try poll events waiting for e certain time
Detailed Description
template<int T_Size>
class zpp::poll_event_set< T_Size >
A set of poll events.
Parameters
Size the size of the set
Definition at line 37 of file poll_event_set.hpp.
Constructor & Destructor Documentation
poll_event_set() [1/2]
template<int T_Size> zpp::poll_event_set< T_Size >::poll_event_set () inline noexcept
default constructor
Definition at line 46 of file poll_event_set.hpp.
   {
   }
poll_event_set() [2/2]
template<int T_Size> template<class... T_Args> zpp::poll_event_set< T_Size >::poll_event_set (T_Args &&... t) inline noexcept
constructor that takes arguments for initialization
Parameters
t the arguments to use for initialization
Definition at line 56 of file poll_event_set.hpp.
   {
     assign(0, std::forward<T_Args>(t)...);
   }
Member Function Documentation
begin()
template<int T_Size> auto zpp::poll_event_set< T_Size >::begin () inline noexcept
Definition at line 40 of file poll_event_set.hpp.
 { return m_events.begin(); }
end()
template<int T_Size> auto zpp::poll_event_set< T_Size >::end () inline noexcept
Definition at line 41 of file poll_event_set.hpp.
 { return m_events.end(); }
operator[]()
template<int T_Size> auto zpp::poll_event_set< T_Size >::operator[] (size_t idx) inline noexcept
access an element of the set
Parameters
idx the index of the event to get
Returns
a poll_event that has a reference to the indexed event
Definition at line 68 of file poll_event_set.hpp.
   {
     __ASSERT_NO_MSG(idx < T_Size);
     return poll_event(&m_events[idx]);
   }
poll()
template<int T_Size> auto zpp::poll_event_set< T_Size >::poll () inline noexcept
poll events waiting for ever
Returns
false on error
Definition at line 79 of file poll_event_set.hpp.
   {
     return poll(K_FOREVER);
   }
Referenced by zpp::poll_event_set< T_Size >::try_poll(), and zpp::poll_event_set< T_Size >::try_poll_for().
try_poll()
template<int T_Size> auto zpp::poll_event_set< T_Size >::try_poll () inline noexcept
try poll events without waiting
Returns
false on error
Definition at line 89 of file poll_event_set.hpp.
   {
     return poll(K_NO_WAIT);
   }
References zpp::poll_event_set< T_Size >::poll().
try_poll_for()
template<int T_Size> template<class T_Rep , class T_Period > auto zpp::poll_event_set< T_Size >::try_poll_for (const std::chrono::duration< T_Rep, T_Period > & timeout) inline noexcept
try poll events waiting for e certain time
Parameters
timeout the time to wait
Returns
false on error
Definition at line 102 of file poll_event_set.hpp.
   {
     using namespace std::chrono;
     return poll(to_timeout(timeout));
   }
References zpp::poll_event_set< T_Size >::poll(), and zpp::to_timeout().
The documentation for this class was generated from the following file:
include/zpp/poll_event_set.hpp