zpp: zpp::thread_id Class Reference
zpp::thread_id Class Reference
Thead ID.
#include <thread_id.hpp>
Public Member Functions
thread_id (const thread_id &) noexcept=default
thread_id (thread_id &&) noexcept=default
thread_id & operator= (const thread_id &) noexcept=default
thread_id & operator= (thread_id &&) noexcept=default
constexpr thread_id () noexcept
Default constructor inializing ID to K_ANY.
constexpr thread_id (k_tid_t tid) noexcept
Constructor inializing ID to tid.
constexpr operator bool () const noexcept
test if the ID is valid
constexpr auto native_handle () const noexcept
Get the Zephyr native ID value.
Static Public Member Functions
constexpr static thread_id any () noexcept
Create an ID with value K_ANY.
Detailed Description
Thead ID.
Definition at line 18 of file thread_id.hpp.
Constructor & Destructor Documentation
thread_id() [1/4]
zpp::thread_id::thread_id (const thread_id &) default noexcept
thread_id() [2/4]
zpp::thread_id::thread_id (thread_id &&) default noexcept
thread_id() [3/4]
constexpr zpp::thread_id::thread_id () inline constexpr noexcept
Default constructor inializing ID to K_ANY.
Definition at line 28 of file thread_id.hpp.
   {
   }
Referenced by any().
thread_id() [4/4]
constexpr zpp::thread_id::thread_id (k_tid_t tid) inline explicit constexpr noexcept
Constructor inializing ID to tid.
Parameters
tid The ID to use for inialization
Definition at line 37 of file thread_id.hpp.
     : m_tid(tid)
   {
   }
Member Function Documentation
any()
constexpr static thread_id zpp::thread_id::any () inline static constexpr noexcept
Create an ID with value K_ANY.
Returns
An ID with value K_ANY
Definition at line 57 of file thread_id.hpp.
   {
     return thread_id(K_ANY);
   }
References thread_id().
Referenced by zpp::thread::thread(), zpp::thread::abort(), zpp::thread::detach(), and zpp::thread::operator=().
native_handle()
constexpr auto zpp::thread_id::native_handle () const inline constexpr noexcept
Get the Zephyr native ID value.
Returns
The native ID value
Definition at line 67 of file thread_id.hpp.
   {
     return m_tid;
   }
operator bool()
constexpr zpp::thread_id::operator bool () const inline explicit constexpr noexcept
test if the ID is valid
Returns
false if the ID equals K_ANY
Definition at line 47 of file thread_id.hpp.
   {
     return m_tid != K_ANY;
   }
operator=() [1/2]
thread_id& zpp::thread_id::operator= (const thread_id &) default noexcept
operator=() [2/2]
thread_id& zpp::thread_id::operator= (thread_id &&) default noexcept
The documentation for this class was generated from the following file:
include/zpp/thread_id.hpp