zpp: zpp::condition_variable_base< T_ConditionVariable > Class Template Reference
zpp::condition_variable_base< T_ConditionVariable > Class Template Reference
A condition variable CRTP base class.
#include <condition_variable.hpp>
Public Types
using native_type = struct k_condvar
using native_pointer = native_type *
using native_const_pointer = native_type const *
Public Member Functions
auto notify_one () noexcept
Notify one waiter.
auto notify_all () noexcept
Notify all waiters.
template<class T_Mutex >
auto wait (T_Mutex &m) noexcept
wait for ever until the variable is signaled.
template<class T_Mutex , class T_Rep , class T_Period >
auto try_wait_for (T_Mutex &m, const std::chrono::duration< T_Rep, T_Period > &timeout) noexcept
Try waiting with a timeout to see if the variable is signaled.
template<class T_Mutex , class T_Predecate >
auto wait (T_Mutex &m, T_Predecate pred) noexcept
wait for ever until the variable is signaled.
template<class T_Mutex , class T_Rep , class T_Period , class T_Predecate >
auto try_wait_for (T_Mutex &m, const std::chrono::duration< T_Rep, T_Period > &timeout, T_Predecate pred) noexcept
Try waiting with a timeout to see if the variable is signaled.
auto native_handle () noexcept -> native_pointer
get the native zephyr k_condvar pointer.
auto native_handle () const noexcept -> native_const_pointer
get the native zephyr k_condvar pointer.
condition_variable_base (const condition_variable_base &)=delete
condition_variable_base (condition_variable_base &&)=delete
condition_variable_base & operator= (const condition_variable_base &)=delete
condition_variable_base & operator= (condition_variable_base &&)=delete
Protected Member Functions
constexpr condition_variable_base () noexcept=default
Protected default constructor so only derived classes can be created.
Detailed Description
template<typename T_ConditionVariable>
class zpp::condition_variable_base< T_ConditionVariable >
A condition variable CRTP base class.
Definition at line 26 of file condition_variable.hpp.
Member Typedef Documentation
native_const_pointer
template<typename T_ConditionVariable > using zpp::condition_variable_base< T_ConditionVariable >::native_const_pointer = native_type const *
Definition at line 31 of file condition_variable.hpp.
native_pointer
template<typename T_ConditionVariable > using zpp::condition_variable_base< T_ConditionVariable >::native_pointer = native_type*
Definition at line 30 of file condition_variable.hpp.
native_type
template<typename T_ConditionVariable > using zpp::condition_variable_base< T_ConditionVariable >::native_type = struct k_condvar
Definition at line 29 of file condition_variable.hpp.
Constructor & Destructor Documentation
condition_variable_base() [1/3]
template<typename T_ConditionVariable > constexpr zpp::condition_variable_base< T_ConditionVariable >::condition_variable_base () constexpr protected default noexcept
Protected default constructor so only derived classes can be created.
condition_variable_base() [2/3]
template<typename T_ConditionVariable > zpp::condition_variable_base< T_ConditionVariable >::condition_variable_base (const condition_variable_base< T_ConditionVariable > &) delete
condition_variable_base() [3/3]
template<typename T_ConditionVariable > zpp::condition_variable_base< T_ConditionVariable >::condition_variable_base (condition_variable_base< T_ConditionVariable > &&) delete
Member Function Documentation
native_handle() [1/2]
template<typename T_ConditionVariable > auto zpp::condition_variable_base< T_ConditionVariable >::native_handle () const -> native_const_pointer inline noexcept
get the native zephyr k_condvar pointer.
Returns
A pointer to the zephyr k_condvar pointer.
Definition at line 219 of file condition_variable.hpp.
   {
     return static_cast<const T_ConditionVariable*>(this)->native_handle();
   }
References zpp::condition_variable_base< T_ConditionVariable >::native_handle().
native_handle() [2/2]
template<typename T_ConditionVariable > auto zpp::condition_variable_base< T_ConditionVariable >::native_handle () -> native_pointer inline noexcept
get the native zephyr k_condvar pointer.
Returns
A pointer to the zephyr k_condvar pointer.
Definition at line 209 of file condition_variable.hpp.
   {
     return static_cast<T_ConditionVariable*>(this)->native_handle();
   }
Referenced by zpp::condition_variable_base< T_ConditionVariable >::native_handle(), zpp::condition_variable_base< T_ConditionVariable >::notify_all(), zpp::condition_variable_base< T_ConditionVariable >::notify_one(), zpp::condition_variable_base< T_ConditionVariable >::try_wait_for(), and zpp::condition_variable_base< T_ConditionVariable >::wait().
notify_all()
template<typename T_ConditionVariable > auto zpp::condition_variable_base< T_ConditionVariable >::notify_all () inline noexcept
Notify all waiters.
Returns
true if successfull.
Definition at line 63 of file condition_variable.hpp.
   {
     result<void, error_code> res;
     auto rc = k_condvar_broadcast(native_handle());
     if (rc == 0) {
       res.assign_value();
     } else {
       res.assign_error(to_error_code(-rc));
     }
     return res;
   }
References zpp::result< T_Ok, T_Error >::assign_error(), zpp::result< T_Ok, T_Error >::assign_value(), zpp::condition_variable_base< T_ConditionVariable >::native_handle(), and zpp::to_error_code().
notify_one()
template<typename T_ConditionVariable > auto zpp::condition_variable_base< T_ConditionVariable >::notify_one () inline noexcept
Notify one waiter.
Returns
true if successfull.
Definition at line 44 of file condition_variable.hpp.
   {
     result<void, error_code> res;
     auto rc = k_condvar_signal(native_handle());
     if (rc == 0) {
       res.assign_value();
     } else {
       res.assign_error(to_error_code(-rc));
     }
     return res;
   }
References zpp::result< T_Ok, T_Error >::assign_error(), zpp::result< T_Ok, T_Error >::assign_value(), zpp::condition_variable_base< T_ConditionVariable >::native_handle(), and zpp::to_error_code().
operator=() [1/2]
template<typename T_ConditionVariable > condition_variable_base& zpp::condition_variable_base< T_ConditionVariable >::operator= (condition_variable_base< T_ConditionVariable > &&) delete
operator=() [2/2]
template<typename T_ConditionVariable > condition_variable_base& zpp::condition_variable_base< T_ConditionVariable >::operator= (const condition_variable_base< T_ConditionVariable > &) delete
try_wait_for() [1/2]
template<typename T_ConditionVariable > template<class T_Mutex , class T_Rep , class T_Period > auto zpp::condition_variable_base< T_ConditionVariable >::try_wait_for (T_Mutex & m, const std::chrono::duration< T_Rep, T_Period > & timeout) inline noexcept
Try waiting with a timeout to see if the variable is signaled.
Parameters
m The mutex to use
timeout The time to wait before returning
Returns
true if successfull.
Definition at line 114 of file condition_variable.hpp.
   {
     using namespace std::chrono;
     result<void, error_code> res;
     auto h = m.native_handle();
     if (h == nullptr) {
       res.assign_error(error_code::k_inval);
     } else {
       auto rc = k_condvar_wait(native_handle(), h, to_timeout(timeout));
       if (rc == 0) {
         res.assign_value();
       } else {
         res.assign_error(to_error_code(-rc));
       }
     }
     return res;
   }
References zpp::result< T_Ok, T_Error >::assign_error(), zpp::result< T_Ok, T_Error >::assign_value(), zpp::k_inval, zpp::condition_variable_base< T_ConditionVariable >::native_handle(), zpp::to_error_code(), and zpp::to_timeout().
try_wait_for() [2/2]
template<typename T_ConditionVariable > template<class T_Mutex , class T_Rep , class T_Period , class T_Predecate > auto zpp::condition_variable_base< T_ConditionVariable >::try_wait_for (T_Mutex & m, const std::chrono::duration< T_Rep, T_Period > & timeout, T_Predecate pred) inline noexcept
Try waiting with a timeout to see if the variable is signaled.
Parameters
m The mutex to use
timeout The time to wait before returning
pred The predecate that must be true before the wait returns
Returns
true if successfull.
Definition at line 178 of file condition_variable.hpp.
   {
     using namespace std::chrono;
     result<void, error_code> res;
     auto h = m.native_handle();
     if (h == nullptr) {
       res.assign_error(error_code::k_inval);
     } else {
       while(pred() == false) {
         auto rc = k_condvar_wait(native_handle(), h, to_timeout(timeout));
         if (rc != 0) {
           res.assign_error(to_error_code(-rc));
           return res;
         }
         // TODO update timeout
       }
       res.assign_value();
     }
     return res;
   }
References zpp::result< T_Ok, T_Error >::assign_error(), zpp::result< T_Ok, T_Error >::assign_value(), zpp::k_inval, zpp::condition_variable_base< T_ConditionVariable >::native_handle(), zpp::to_error_code(), and zpp::to_timeout().
wait() [1/2]
template<typename T_ConditionVariable > template<class T_Mutex > auto zpp::condition_variable_base< T_ConditionVariable >::wait (T_Mutex & m) inline noexcept
wait for ever until the variable is signaled.
Parameters
m The mutex to use
Returns
true if successfull.
Definition at line 85 of file condition_variable.hpp.
   {
     result<void, error_code> res;
     auto h = m.native_handle();
     if (h == nullptr) {
       res.assign_error(error_code::k_inval);
     } else {
       auto rc = k_condvar_wait(native_handle(), h, K_FOREVER);
       if (rc == 0) {
         res.assign_value();
       } else {
         res.assign_error(to_error_code(-rc));
       }
     }
     return res;
   }
References zpp::result< T_Ok, T_Error >::assign_error(), zpp::result< T_Ok, T_Error >::assign_value(), zpp::k_inval, zpp::condition_variable_base< T_ConditionVariable >::native_handle(), and zpp::to_error_code().
wait() [2/2]
template<typename T_ConditionVariable > template<class T_Mutex , class T_Predecate > auto zpp::condition_variable_base< T_ConditionVariable >::wait (T_Mutex & m, T_Predecate pred) inline noexcept
wait for ever until the variable is signaled.
Parameters
m The mutex to use
pred The predecate that must be true before the wait returns
Returns
true if successfull.
Definition at line 145 of file condition_variable.hpp.
   {
     result<void, error_code> res;
     auto h = m.native_handle();
     if (h == nullptr) {
       res.assign_error(error_code::k_inval);
     } else {
       while (pred() == false) {
         auto rc = k_condvar_wait(native_handle(), h, K_FOREVER);
         if (rc != 0) {
           res.assign_error(to_error_code(-rc));
           return res;
         }
       }
       res.assign_value();
     }
     return res;
   }
References zpp::result< T_Ok, T_Error >::assign_error(), zpp::result< T_Ok, T_Error >::assign_value(), zpp::k_inval, zpp::condition_variable_base< T_ConditionVariable >::native_handle(), and zpp::to_error_code().
The documentation for this class was generated from the following file:
include/zpp/condition_variable.hpp