zpp: zpp::internal Namespace Reference
zpp::internal Namespace Reference
Functions
void print_arg () noexcept
void print_arg (bool v) noexcept
void print_arg (float v) noexcept
void print_arg (double v) noexcept
void print_arg (char v) noexcept
void print_arg (const char *v) noexcept
void print_arg (const void *v) noexcept
void print_arg (uint8_t v) noexcept
void print_arg (int8_t v) noexcept
void print_arg (uint16_t v) noexcept
void print_arg (int16_t v) noexcept
void print_arg (uint32_t v) noexcept
void print_arg (int32_t v) noexcept
void print_arg (uint64_t v) noexcept
void print_arg (int64_t v) noexcept
template<class T_Rep , class T_Period >
void print_arg (std::chrono::duration< T_Rep, T_Period > v)
template<class T_Clock >
void print_arg (std::chrono::time_point< T_Clock > v)
void print_helper (const char *fmt) noexcept
template<class T_FirstArg , class ... T_Args>
void print_helper (const char *fmt, T_FirstArg &&first, T_Args &&... args) noexcept
Function Documentation
print_arg() [1/17]
void zpp::internal::print_arg () inline noexcept
Definition at line 21 of file fmt.hpp.
 { }
Referenced by print_arg(), and print_helper().
print_arg() [2/17]
void zpp::internal::print_arg (bool v) inline noexcept
Definition at line 22 of file fmt.hpp.
 { printk("%d", (int)v); }
print_arg() [3/17]
void zpp::internal::print_arg (char v) inline noexcept
Definition at line 25 of file fmt.hpp.
 { printk("%c", v); }
print_arg() [4/17]
void zpp::internal::print_arg (const char * v) inline noexcept
Definition at line 26 of file fmt.hpp.
 { printk("%s", v); }
print_arg() [5/17]
void zpp::internal::print_arg (const void * v) inline noexcept
Definition at line 27 of file fmt.hpp.
 { printk("%p", v); }
print_arg() [6/17]
void zpp::internal::print_arg (double v) inline noexcept
Definition at line 24 of file fmt.hpp.
 { printk("%g", v); }
print_arg() [7/17]
void zpp::internal::print_arg (float v) inline noexcept
Definition at line 23 of file fmt.hpp.
 { printk("%f", v); }
print_arg() [8/17]
void zpp::internal::print_arg (int16_t v) inline noexcept
Definition at line 31 of file fmt.hpp.
 { printk("%d", (int32_t)v); }
print_arg() [9/17]
void zpp::internal::print_arg (int32_t v) inline noexcept
Definition at line 33 of file fmt.hpp.
 { printk("%d", v); }
print_arg() [10/17]
void zpp::internal::print_arg (int64_t v) inline noexcept
Definition at line 35 of file fmt.hpp.
 { printk("%lld", v); }
print_arg() [11/17]
void zpp::internal::print_arg (int8_t v) inline noexcept
Definition at line 29 of file fmt.hpp.
 { printk("%d", (int32_t)v); }
print_arg() [12/17]
template<class T_Rep , class T_Period > void zpp::internal::print_arg (std::chrono::duration< T_Rep, T_Period > v) inline
Definition at line 38 of file fmt.hpp.
 {
   using namespace std::chrono;
   auto s = duration_cast<seconds>(v);
   v -= duration_cast<decltype(v)>(s);
   auto ms = duration_cast<milliseconds>(v);
   v -= duration_cast<decltype(v)>(ms);
   auto us = duration_cast<microseconds>(v);
   v -= duration_cast<decltype(v)>(us);
   auto ns = duration_cast<nanoseconds>(v);
   printk("%d.%03d%03d%03ds",
     (int)s.count(), (int)ms.count(),
     (int)us.count(), (int)ns.count());
 }
print_arg() [13/17]
template<class T_Clock > void zpp::internal::print_arg (std::chrono::time_point< T_Clock > v) inline
Definition at line 56 of file fmt.hpp.
 {
   print_arg(v.time_since_epoch());
 }
References print_arg().
print_arg() [14/17]
void zpp::internal::print_arg (uint16_t v) inline noexcept
Definition at line 30 of file fmt.hpp.
 { printk("%d", (uint32_t)v); }
print_arg() [15/17]
void zpp::internal::print_arg (uint32_t v) inline noexcept
Definition at line 32 of file fmt.hpp.
 { printk("%d", v); }
print_arg() [16/17]
void zpp::internal::print_arg (uint64_t v) inline noexcept
Definition at line 34 of file fmt.hpp.
 { printk("%lld", v); }
print_arg() [17/17]
void zpp::internal::print_arg (uint8_t v) inline noexcept
Definition at line 28 of file fmt.hpp.
 { printk("%d", (uint32_t)v); }
print_helper() [1/2]
void zpp::internal::print_helper (const char * fmt) inline noexcept
Definition at line 61 of file fmt.hpp.
 {
   printk("%s", fmt);
 }
Referenced by zpp::print(), and print_helper().
print_helper() [2/2]
template<class T_FirstArg , class ... T_Args> void zpp::internal::print_helper (const char * fmt, T_FirstArg && first, T_Args &&... args) inline noexcept
Definition at line 67 of file fmt.hpp.
 {
   enum class state { normal, format, open_brace, close_brace, done };
   state s = state::normal;
   size_t n = 0;
   while (true) {
     char c = fmt[n++];
     if (c == '\0') {
       return;
     }
     switch (s) {
     case state::normal:
       switch (c) {
       case '{':
         s = state::open_brace;
         break;
       case '}':
         s = state::close_brace;
         break;
       default:
         printk("%c", c);
         break;
       }
       break;
     case state::open_brace:
       switch(c) {
       case '{':
         s = state::normal;
         printk("{");
         break;
       case '}':
         s = state::done;
         break;
       default:
         s = state::format;
         break;
       }
       break;
     case state::close_brace:
       if (c == '}') {
         printk("}");
       }
       s = state::normal;
       break;
     case state::format:
       switch (c) {
       case '}':
         s = state::done;
         break;
       default:
         break;
       }
       break;
     case state::done:
       break;
     }
     if (s == state::done) {
       break;
     }
   }
   print_arg(std::forward<T_FirstArg>(first));
   print_helper(&(fmt[n]), std::forward<T_Args>(args)...);
 }
References print_arg(), and print_helper().