zpp: zpp Namespace Reference
zpp Namespace Reference
Namespaces
internal
this_thread
provide functions that access the current thread of execution.
Classes
class atomic_bitset
class wrapping an atomic_var_t array
class atomic_var
class wrapping an atomic_var_t
class uptime_clock
Clock measuring elapsed time since the system booted.
class cycle_clock
Clock representing the system’s hardware clock.
class condition_variable_base
A condition variable CRTP base class.
class condition_variable
A condition variable class.
class condition_variable_ref
A class using a reference to another native condition variable or zpp::condition_variable.
class fifo_base
Fifo CRTP base class.
class fifo
fifo that manages a k_fifo object
class fifo_ref
fifo that references a k_fifo object
class futex_base
A CRTP futex base class.
class futex
A futex class.
class futex_ref
A futex class referencing another futex object.
class base_heap
Heap memory allocater CRTP base class.
class heap
heap class
class heap_ref
heap reference class
class lock_guard
lock_guard using zpp::mutex as a lock.
class mem_slab_base
Allocator that uses k_mem_slab for memory.
class mem_slab
A memory slab class.
class mem_slab_ref
A mem_slab class referencing another mem slab object.
class mutex_base
A recursive mutex CRTP base class.
class mutex
A recursive mutex class.
class mutex_ref
A recursive mutex class borrowing the native mutex.
class poll_event
wrapper class around a k_poll_event
class poll_event_set
A set of poll events.
class poll_signal_base
CRTP base class for poll_signals.
class poll_signal
class owning a k_poll_signal
class poll_signal_ref
class wrapping a k_poll_signal
class error_result
helper class for error result
class result
result class
class result< void, T_Error >
result class
class sched_lock_guard
Guard to automatically lock/unlock scheduler.
class sem_base
Counting semaphore base class.
class sem
A counting semaphore class.
class sem_ref
A counting semaphore class borrowing the native sem.
class sys_mutex_base
A userspace mutex class.
class sys_mutex
A recursive mutex class.
class sys_mutex_ref
A recursive mutex class borrowing the native mutex.
class thread
The class thread repecents a single Zephyr thread.
struct thread_start_delay
class thread_attr
Thread creation attributes.
class thread_data
thread_data holds the stack and thread control block memory
class thread_id
Thead ID.
class thread_prio
Thread priority.
class thread_stack
thread_stack holds the stack and thread control block memory
class timer_base
base class for the timer class
class timer
timer class with expire and stop callbacks
class basic_timer
timer class with only an expire callback
class sync_timer
timer class with no callbacks used for syncing only
class unique_lock
zpp::unique_lock using zpp::mutex as a lock.
Enumerations
enum class error_code {
k_perm = EPERM , k_noent = ENOENT , k_srch = ESRCH , k_intr = EINTR ,
k_io = EIO , k_nxio = ENXIO , k_2big = E2BIG , k_noexec = ENOEXEC ,
k_badf = EBADF , k_child = ECHILD , k_again = EAGAIN , k_nomem = ENOMEM ,
k_acces = EACCES , k_fault = EFAULT , k_notblk = ENOTBLK , k_busy = EBUSY ,
k_exits = EEXIST , k_xdev = EXDEV , k_nodev = ENODEV , k_notdir = ENOTDIR ,
k_isdir = EISDIR , k_inval = EINVAL , k_nfile = ENFILE , k_mfile = EMFILE ,
k_notty = ENOTTY , k_txtbsy = ETXTBSY , k_fbig = EFBIG , k_nospc = ENOSPC ,
k_spipe = ESPIPE , k_rofs = EROFS , k_mlink = EMLINK , k_pipe = EPIPE ,
k_dom = EDOM , k_range = ERANGE , k_nomsg = ENOMSG , k_deadlk = EDEADLK ,
k_nolck = ENOLCK , k_nostr = ENOSTR , k_nodata = ENODATA , k_time = ETIME ,
k_nosr = ENOSR , k_proto = EPROTO , k_badmsg = EBADMSG , k_nosys = ENOSYS ,
k_notempty = ENOTEMPTY , k_nametoolong = ENAMETOOLONG , k_loop = ELOOP , k_opnotsupp = EOPNOTSUPP ,
k_pfnosupport = EPFNOSUPPORT , k_connreset = ECONNRESET , k_nobufs = ENOBUFS , k_afnosupport = EAFNOSUPPORT ,
k_prototype = EPROTOTYPE , k_notsock = ENOTSOCK , k_noprotoopt = ENOPROTOOPT , k_shutdown = ESHUTDOWN ,
k_connrefused = ECONNREFUSED , k_addrinuse = EADDRINUSE , k_connaborted = ECONNABORTED , k_netunreach = ENETUNREACH ,
k_netdown = ENETDOWN , k_timeout = ETIMEDOUT , k_hostdown = EHOSTDOWN , k_hostunreach = EHOSTUNREACH ,
k_inprogress = EINPROGRESS , k_already = EALREADY , k_destaddrreq = EDESTADDRREQ , k_msgsize = EMSGSIZE ,
k_protonosupport = EPROTONOSUPPORT , k_socktnosupport = ESOCKTNOSUPPORT , k_addrnotavail = EADDRNOTAVAIL , k_netreset = ENETRESET ,
k_isconn = EISCONN , k_notconn = ENOTCONN , k_toomanyrefs = ETOOMANYREFS , k_notsup = ENOTSUP ,
k_ilseq = EILSEQ , k_overflow = EOVERFLOW , k_canceled = ECANCELED , k_wouldblock = EWOULDBLOCK
}
enum with zephyr error codes
enum class thread_suspend { yes , no }
enum class thread_essential { yes , no }
enum class thread_user { yes , no }
enum class thread_inherit_perms { yes , no }
enum class thread_fp_regs { yes , no }
enum class thread_sse_regs { yes , no }
Functions
template<class T_Rep , class T_Period >
constexpr k_ticks_t to_tick (const std::chrono::duration< T_Rep, T_Period > &d) noexcept
convert a duration to tick
template<class T_Rep , class T_Period >
constexpr k_timeout_t to_timeout (const std::chrono::duration< T_Rep, T_Period > &d) noexcept
convert a duration to tick
constexpr error_code to_error_code (int v) noexcept
template<class ... T_Args>
void print (const char *fmt, T_Args &&... args) noexcept
simple typesafe print function
template<class... T_Args>
poll_event_set (T_Args &&... t) noexcept -> poll_event_set< sizeof...(T_Args)>
try poll events waiting for e certain time
template<typename T_Ok , typename T_Error >
constexpr bool operator== (const result< T_Ok, T_Error > &lhs, bool rhs) noexcept
compare result with bool
template<typename T_Ok , typename T_Error >
constexpr bool operator== (bool lhs, const result< T_Ok, T_Error > &rhs) noexcept
compare result with bool
template<typename T_Ok , typename T_Error >
constexpr bool operator!= (const result< T_Ok, T_Error > &lhs, bool rhs) noexcept
compare result with bool
template<typename T_Ok , typename T_Error >
constexpr bool operator!= (bool lhs, const result< T_Ok, T_Error > &rhs) noexcept
compare result with bool
void sched_lock () noexcept
Lock the scheduler.
void sched_unlock () noexcept
Unlock the scheduler.
template<class T >
std::decay< T >::type decay_copy (T &&v) noexcept
constexpr bool operator== (const thread_id &lhs, const thread_id &rhs) noexcept
Compare if two ID are equal.
constexpr bool operator!= (const thread_id &lhs, const thread_id &rhs) noexcept
Compare if two ID are not equal.
void print_arg (thread_id id) noexcept
Helper to output the ID with zpp::print("{}", id)
constexpr bool operator== (const thread_prio &lhs, const thread_prio &rhs) noexcept
Compare if two priorities are equal.
constexpr bool operator!= (const thread_prio &lhs, const thread_prio &rhs) noexcept
Compare if two priorities are not equal.
constexpr thread_prio operator- (thread_prio lhs, int rhs) noexcept
Reduce priority by rhs.
constexpr thread_prio operator+ (thread_prio lhs, int rhs) noexcept
Increase priority by rhs.
void print_arg (thread_prio prio) noexcept
Helper to output the priority with zpp::print("{}", prio)
auto make_timer () noexcept
create sync_timer object
template<class T_ExpireCallback >
auto make_timer (T_ExpireCallback &&ecb) noexcept
create basic_timer object
template<class T_ExpireCallback , class T_StopCallback >
auto make_timer (T_ExpireCallback &&ecb, T_StopCallback &&scb) noexcept
create timer object
template<class T_LHS , class T_RHS >
constexpr bool operator== (const T_LHS &lhs, const T_RHS &rhs) noexcept
check if the instances refere to the same native zephyr object handle.
template<class T_LHS , class T_RHS >
constexpr bool operator!= (const T_LHS &lhs, const T_RHS &rhs) noexcept
check if the arguments refere to different native zephyr object handles.
consteval uint32_t power_of_two (uint32_t power) noexcept
calculate a power of 2
consteval bool is_power_of_two (uint32_t value) noexcept
check if a value is a power of two
consteval bool is_multiple_of (uint32_t value, uint32_t base)
Check if a value is a multiple of another value.
Detailed Description
Copyright (c) 2021 Erwin Rol erwin.nosp@m.@erw.nosp@m.inrol.nosp@m..com
SPDX-License-Identifier: Apache-2.0
Copyright (c) 2019 Erwin Rol erwin.nosp@m.@erw.nosp@m.inrol.nosp@m..com
SPDX-License-Identifier: Apache-2.0
Enumeration Type Documentation
error_code
enum zpp::error_code strong
enum with zephyr error codes
Enumerator
k_perm
Not owner.
k_noent
No such file or directory.
k_srch
No such context.
k_intr
Interrupted system call.
k_io
I/O error.
k_nxio
No such device or address.
k_2big
Arg list too long.
k_noexec
Exec format error.
k_badf
Bad file number.
k_child
No children.
k_again
No more contexts.
k_nomem
Not enough core.
k_acces
Permission denied.
k_fault
Bad address.
k_notblk
Block device required.
k_busy
Mount device busy.
k_exits
File exists.
k_xdev
Cross-device link.
k_nodev
No such device.
k_notdir
Not a directory.
k_isdir
Is a directory.
k_inval
Invalid argument.
k_nfile
File table overflow.
k_mfile
Too many open files.
k_notty
Not a typewriter.
k_txtbsy
Text file busy.
k_fbig
File too large.
k_nospc
No space left on device.
k_spipe
Illegal seek.
k_rofs
Read-only file system.
k_mlink
Too many links.
k_pipe
Broken pipe.
k_dom
Argument too large.
k_range
Result too large.
k_nomsg
Unexpected message type.
k_deadlk
Resource deadlock avoided.
k_nolck
No locks available.
k_nostr
STREAMS device required.
k_nodata
Missing expected message data.
k_time
STREAMS timeout occurred.
k_nosr
Insufficient memory.
k_proto
Generic STREAMS error.
k_badmsg
Invalid STREAMS message.
k_nosys
Function not implemented.
k_notempty
Directory not empty.
k_nametoolong
File name too long.
k_loop
Too many levels of symbolic links.
k_opnotsupp
Operation not supported on socket.
k_pfnosupport
Protocol family not supported.
k_connreset
Connection reset by peer.
k_nobufs
No buffer space available.
k_afnosupport
Addr family not supported.
k_prototype
Protocol wrong type for socket.
k_notsock
Socket operation on non-socket.
k_noprotoopt
Protocol not available.
k_shutdown
Can’t send after socket shutdown.
k_connrefused
Connection refused.
k_addrinuse
Address already in use.
k_connaborted
Software caused connection abort.
k_netunreach
Network is unreachable.
k_netdown
Network is down.
k_timeout
Connection timed out.
k_hostdown
Host is down.
k_hostunreach
No route to host.
k_inprogress
Operation now in progress.
k_already
Operation already in progress.
k_destaddrreq
Destination address required.
k_msgsize
Message size.
k_protonosupport
Protocol not supported.
k_socktnosupport
Socket type not supported.
k_addrnotavail
Can’t assign requested address.
k_netreset
Network dropped connection on reset.
k_isconn
Socket is already connected.
k_notconn
Socket is not connected.
k_toomanyrefs
Too many references: can’t splice.
k_notsup
Unsupported value.
k_ilseq
Illegal byte sequence.
k_overflow
Value overflow.
k_canceled
Operation canceled.
k_wouldblock
Operation would block.
Definition at line 19 of file error_code.hpp.
                       {
     k_perm            = EPERM,
     k_noent           = ENOENT,
     k_srch            = ESRCH,
     k_intr            = EINTR,
     k_io              = EIO,
     k_nxio            = ENXIO,
     k_2big            = E2BIG,
     k_noexec          = ENOEXEC,
     k_badf            = EBADF,
     k_child           = ECHILD,
     k_again           = EAGAIN,
     k_nomem           = ENOMEM,
     k_acces           = EACCES,
     k_fault           = EFAULT,
     k_notblk          = ENOTBLK,
     k_busy            = EBUSY,
     k_exits           = EEXIST,
     k_xdev            = EXDEV,
     k_nodev           = ENODEV,
     k_notdir          = ENOTDIR,
     k_isdir           = EISDIR,
     k_inval           = EINVAL,
     k_nfile           = ENFILE,
     k_mfile           = EMFILE,
     k_notty           = ENOTTY,
     k_txtbsy          = ETXTBSY,
     k_fbig            = EFBIG,
     k_nospc           = ENOSPC,
     k_spipe           = ESPIPE,
     k_rofs            = EROFS,
     k_mlink           = EMLINK,
     k_pipe            = EPIPE,
     k_dom             = EDOM,
     k_range           = ERANGE,
     k_nomsg           = ENOMSG,
     k_deadlk          = EDEADLK,
     k_nolck           = ENOLCK,
     k_nostr           = ENOSTR,
     k_nodata          = ENODATA,
     k_time            = ETIME,
     k_nosr            = ENOSR,
     k_proto           = EPROTO,
     k_badmsg          = EBADMSG,
     k_nosys           = ENOSYS,
     k_notempty        = ENOTEMPTY,
     k_nametoolong     = ENAMETOOLONG,
     k_loop            = ELOOP,
     k_opnotsupp       = EOPNOTSUPP,
     k_pfnosupport     = EPFNOSUPPORT,
     k_connreset       = ECONNRESET,
     k_nobufs          = ENOBUFS,
     k_afnosupport     = EAFNOSUPPORT,
     k_prototype       = EPROTOTYPE,
     k_notsock         = ENOTSOCK,
     k_noprotoopt      = ENOPROTOOPT,
     k_shutdown        = ESHUTDOWN,
     k_connrefused     = ECONNREFUSED,
     k_addrinuse       = EADDRINUSE,
     k_connaborted     = ECONNABORTED,
     k_netunreach      = ENETUNREACH,
     k_netdown         = ENETDOWN,
     k_timeout         = ETIMEDOUT,
     k_hostdown        = EHOSTDOWN,
     k_hostunreach     = EHOSTUNREACH,
     k_inprogress      = EINPROGRESS,
     k_already         = EALREADY,
     k_destaddrreq     = EDESTADDRREQ,
     k_msgsize         = EMSGSIZE,
     k_protonosupport  = EPROTONOSUPPORT,
     k_socktnosupport  = ESOCKTNOSUPPORT,
     k_addrnotavail    = EADDRNOTAVAIL,
     k_netreset        = ENETRESET,
     k_isconn          = EISCONN,
     k_notconn         = ENOTCONN,
     k_toomanyrefs     = ETOOMANYREFS,
     k_notsup          = ENOTSUP,
     k_ilseq           = EILSEQ,
     k_overflow        = EOVERFLOW,
     k_canceled        = ECANCELED,
     k_wouldblock      = EWOULDBLOCK,
 };
thread_essential
enum zpp::thread_essential strong
Enumerator
yes
no
Definition at line 21 of file thread_attr.hpp.
 { yes, no };
thread_fp_regs
enum zpp::thread_fp_regs strong
Enumerator
yes
no
Definition at line 24 of file thread_attr.hpp.
 { yes, no };
thread_inherit_perms
enum zpp::thread_inherit_perms strong
Enumerator
yes
no
Definition at line 23 of file thread_attr.hpp.
 { yes, no };
thread_sse_regs
enum zpp::thread_sse_regs strong
Enumerator
yes
no
Definition at line 25 of file thread_attr.hpp.
 { yes, no };
thread_suspend
enum zpp::thread_suspend strong
Enumerator
yes
no
Definition at line 20 of file thread_attr.hpp.
 { yes, no };
thread_user
enum zpp::thread_user strong
Enumerator
yes
no
Definition at line 22 of file thread_attr.hpp.
 { yes, no };
Function Documentation
decay_copy()
template<class T > std::decay<T>::type zpp::decay_copy (T && v) noexcept
Definition at line 139 of file thread.hpp.
 {
   return std::forward<T>(v);
 }
Referenced by zpp::thread::thread().
is_multiple_of()
consteval bool zpp::is_multiple_of (uint32_t value, uint32_t base)
Check if a value is a multiple of another value.
Parameters
value the value to check
base the base the value should be a multiple of
Returns
true if value is a multiple of base
Definition at line 117 of file utils.hpp.
 {
   if (value == 0 || base == 0) {
     return false;
   } else {
     return (value % base) == 0;
   }
 }
is_power_of_two()
consteval bool zpp::is_power_of_two (uint32_t value) noexcept
check if a value is a power of two
Parameters
value the value to check
Returns
true if value is a power of two
Definition at line 97 of file utils.hpp.
 {
   uint32_t power {0};
   uint32_t calc_val;
   do {
     calc_val = power_of_two(power++);
   } while (calc_val < value);
   return calc_val == value;
 }
References power_of_two().
make_timer() [1/3]
auto zpp::make_timer () inline noexcept
create sync_timer object
Returns
sync_timer object
Definition at line 233 of file timer.hpp.
 {
   return sync_timer();
 }
Referenced by ZTEST().
make_timer() [2/3]
template<class T_ExpireCallback > auto zpp::make_timer (T_ExpireCallback && ecb) inline noexcept
create basic_timer object
Parameters
ecb the expire callback
Returns
basic_timer object
Definition at line 246 of file timer.hpp.
 {
   return basic_timer(std::forward<T_ExpireCallback>(ecb));
 }
make_timer() [3/3]
template<class T_ExpireCallback , class T_StopCallback > auto zpp::make_timer (T_ExpireCallback && ecb, T_StopCallback && scb) inline noexcept
create timer object
Parameters
ecb the expire callback
scb the stop callback
Returns
timer object
Definition at line 260 of file timer.hpp.
 {
   return timer(std::forward<T_ExpireCallback>(ecb), std::forward<T_StopCallback>(scb));
 }
operator!=() [1/5]
template<typename T_Ok , typename T_Error > constexpr bool zpp::operator!= (bool lhs, const result< T_Ok, T_Error > & rhs) constexpr noexcept
compare result with bool
Parameters
lhs the bool value
rhs the result value
Returns
true if lhs is not equal to rhs
Definition at line 694 of file result.hpp.
{
   return bool(lhs) != bool(rhs);
 }
operator!=() [2/5]
template<typename T_Ok , typename T_Error > constexpr bool zpp::operator!= (const result< T_Ok, T_Error > & lhs, bool rhs) constexpr noexcept
compare result with bool
Parameters
lhs the result value
rhs the bool value
Returns
true if lhs is not equal to rhs
Definition at line 681 of file result.hpp.
{
   return bool(lhs) != bool(rhs);
 }
operator!=() [3/5]
template<class T_LHS , class T_RHS > constexpr bool zpp::operator!= (const T_LHS & lhs, const T_RHS & rhs) constexpr noexcept
check if the arguments refere to different native zephyr object handles.
Returns
true if they refer to different native zephyr objects.
Definition at line 50 of file utils.hpp.
 {
   if constexpr (std::is_pointer_v<T_LHS> && std::is_pointer_v<T_RHS>) {
     return lhs != rhs;
   }
   if constexpr (std::is_pointer_v<T_LHS> && !std::is_pointer_v<T_RHS>) {
     return lhs != rhs.native_handle();
   }
   if constexpr (!std::is_pointer_v<T_LHS> && std::is_pointer_v<T_RHS>) {
     return lhs.native_handle() != rhs;
   }
   if constexpr (!std::is_pointer_v<T_LHS> && !std::is_pointer_v<T_RHS>) {
     return lhs.native_handle() != rhs.native_handle();
   }
   static_assert(true, "should never be reached");
   return false;
 }
operator!=() [4/5]
constexpr bool zpp::operator!= (const thread_id & lhs, const thread_id & rhs) constexpr noexcept
Compare if two ID are not equal.
Parameters
lhs Left hand side for comparison
rhs Right hand side for comparison
Returns
true is lhs and rhs are not equal
Definition at line 98 of file thread_id.hpp.
 {
   return (lhs.native_handle() != rhs.native_handle());
 }
operator!=() [5/5]
constexpr bool zpp::operator!= (const thread_prio & lhs, const thread_prio & rhs) constexpr noexcept
Compare if two priorities are not equal.
Parameters
lhs Left hand side for comparison
rhs Right hand side for comparison
Returns
true is lhs and rhs are not equal
Definition at line 219 of file thread_prio.hpp.
 {
   return (lhs.native_value() != rhs.native_value());
 }
operator+()
constexpr thread_prio zpp::operator+ (thread_prio lhs, int rhs) constexpr noexcept
Increase priority by rhs.
Parameters
lhs Left hand side for the operation
rhs Right hand side for the operation
Returns
A priority value that is rhs more prior than lhs
Definition at line 247 of file thread_prio.hpp.
 {
   return thread_prio(lhs.native_value() - rhs);
 }
operator-()
constexpr thread_prio zpp::operator- (thread_prio lhs, int rhs) constexpr noexcept
Reduce priority by rhs.
Parameters
lhs Left hand side for the operation
rhs Right hand side for the operation
Returns
A priority value that is rhs less prior than lhs
Definition at line 233 of file thread_prio.hpp.
 {
   return thread_prio(lhs.native_value() + rhs);
 }
operator==() [1/5]
template<typename T_Ok , typename T_Error > constexpr bool zpp::operator== (bool lhs, const result< T_Ok, T_Error > & rhs) constexpr noexcept
compare result with bool
Parameters
lhs the bool value
rhs the result value
Returns
true if lhs is equal to rhs
Definition at line 668 of file result.hpp.
{
   return bool(lhs) == bool(rhs);
 }
operator==() [2/5]
template<typename T_Ok , typename T_Error > constexpr bool zpp::operator== (const result< T_Ok, T_Error > & lhs, bool rhs) constexpr noexcept
compare result with bool
Parameters
lhs the result value
rhs the bool value
Returns
true if lhs is equal to rhs
Definition at line 655 of file result.hpp.
{
   return bool(lhs) == bool(rhs);
 }
operator==() [3/5]
template<class T_LHS , class T_RHS > constexpr bool zpp::operator== (const T_LHS & lhs, const T_RHS & rhs) constexpr noexcept
check if the instances refere to the same native zephyr object handle.
Returns
true if they refer to the same native zephyr object.
Definition at line 21 of file utils.hpp.
 {
   if constexpr (std::is_pointer_v<T_LHS> && std::is_pointer_v<T_RHS>) {
     return lhs == rhs;
   }
   if constexpr (std::is_pointer_v<T_LHS> && !std::is_pointer_v<T_RHS>) {
     return lhs == rhs.native_handle();
   }
   if constexpr (!std::is_pointer_v<T_LHS> && std::is_pointer_v<T_RHS>) {
     return lhs.native_handle() == rhs;
   }
   if constexpr (!std::is_pointer_v<T_LHS> && !std::is_pointer_v<T_RHS>) {
     return lhs.native_handle() == rhs.native_handle();
   }
   static_assert(true, "should never be reached");
   return true;
 }
operator==() [4/5]
constexpr bool zpp::operator== (const thread_id & lhs, const thread_id & rhs) constexpr noexcept
Compare if two ID are equal.
Parameters
lhs Left hand side for comparison
rhs Right hand side for comparison
Returns
true is lhs and rhs are equal
Definition at line 84 of file thread_id.hpp.
 {
   return (lhs.native_handle() == rhs.native_handle());
 }
operator==() [5/5]
constexpr bool zpp::operator== (const thread_prio & lhs, const thread_prio & rhs) constexpr noexcept
Compare if two priorities are equal.
Parameters
lhs Left hand side for comparison
rhs Right hand side for comparison
Returns
true is lhs and rhs are equal
Definition at line 205 of file thread_prio.hpp.
 {
   return (lhs.native_value() == rhs.native_value());
 }
poll_event_set()
template<class... T_Args> zpp::poll_event_set (T_Args &&... t) -> poll_event_set< sizeof...(T_Args)> noexcept
try poll events waiting for e certain time
Parameters
timeout the time to wait
Returns
false on error
power_of_two()
consteval uint32_t zpp::power_of_two (uint32_t power) noexcept
calculate a power of 2
Parameters
power the power of 2 to calculate
Returns
the power of 2
Definition at line 79 of file utils.hpp.
 {
   uint32_t res = 1;
   for (uint32_t i = 1; i <= power; ++i) {
     res *= 2;
   }
   return res;
 }
Referenced by is_power_of_two().
print()
template<class ... T_Args> void zpp::print (const char * fmt, T_Args &&... args) inline noexcept
simple typesafe print function
print uses the same format string syntax as the fmt C++ lib, just that the feature set is very limited. It only supports {} without any options, for example print("Nr: {}", 1);
Parameters
fmt The format string using {} as place holder
args The needed arguments to print
Definition at line 157 of file fmt.hpp.
 {
   internal::print_helper(fmt, std::forward<T_Args>(args)...);
 }
References zpp::internal::print_helper().
Referenced by main(), and ZTEST().
print_arg() [1/2]
void zpp::print_arg (thread_id id) inline noexcept
Helper to output the ID with zpp::print("{}", id)
Parameters
id The ID to print
Definition at line 109 of file thread_id.hpp.
 {
   printk("%p", id.native_handle());
 }
print_arg() [2/2]
void zpp::print_arg (thread_prio prio) inline noexcept
Helper to output the priority with zpp::print("{}", prio)
Parameters
prio The priority to print
Definition at line 257 of file thread_prio.hpp.
 {
   printk("%d", prio.native_value());
 }
sched_lock()
void zpp::sched_lock () inline noexcept
Lock the scheduler.
Definition at line 18 of file sched.hpp.
 {
   k_sched_lock();
 }
Referenced by zpp::sched_lock_guard::sched_lock_guard().
sched_unlock()
void zpp::sched_unlock () inline noexcept
Unlock the scheduler.
Definition at line 26 of file sched.hpp.
 {
   k_sched_unlock();
 }
Referenced by zpp::sched_lock_guard::~sched_lock_guard().
to_error_code()
constexpr error_code zpp::to_error_code (int v) constexpr noexcept
Definition at line 102 of file error_code.hpp.
 {
   return static_cast<error_code>(v);
 }
Referenced by zpp::thread::join(), zpp::mutex_base< T_Mutex >::lock(), zpp::condition_variable_base< T_ConditionVariable >::notify_all(), zpp::condition_variable_base< T_ConditionVariable >::notify_one(), zpp::thread::set_name(), zpp::mutex_base< T_Mutex >::try_lock(), zpp::mutex_base< T_Mutex >::try_lock_for(), zpp::condition_variable_base< T_ConditionVariable >::try_wait_for(), zpp::mutex_base< T_Mutex >::unlock(), and zpp::condition_variable_base< T_ConditionVariable >::wait().
to_tick()
template<class T_Rep , class T_Period > constexpr k_ticks_t zpp::to_tick (const std::chrono::duration< T_Rep, T_Period > & d) constexpr noexcept
convert a duration to tick
Parameters
d the std::chrono::duration to convert
Returns
the number of tick d represents
Definition at line 72 of file clock.hpp.
 {
   using namespace std::chrono;
   return k_ns_to_ticks_floor64(duration_cast<nanoseconds>(d).count());
 }
Referenced by zpp::thread_attr::set(), and to_timeout().
to_timeout()
template<class T_Rep , class T_Period > constexpr k_timeout_t zpp::to_timeout (const std::chrono::duration< T_Rep, T_Period > & d) constexpr noexcept
convert a duration to tick
Parameters
d the std::chrono::duration to convert
Returns
the number of tick d represents
Definition at line 88 of file clock.hpp.
 {
   return { to_tick(d) };
 }
References to_tick().
Referenced by zpp::this_thread::sleep_for(), zpp::this_thread::sleep_until(), zpp::timer_base::start(), zpp::mem_slab_base< T_MemSlab >::try_allocate_for(), zpp::base_heap< T_Heap >::try_allocate_for(), zpp::mutex_base< T_Mutex >::try_lock_for(), zpp::sys_mutex_base< T_Mutex >::try_lock_for(), zpp::poll_event_set< T_Size >::try_poll_for(), zpp::sem_base< T_Sem >::try_take_for(), zpp::futex_base< T_Futex >::try_wait_for(), and zpp::condition_variable_base< T_ConditionVariable >::try_wait_for().