zpp: zpp::this_thread Namespace Reference
zpp::this_thread Namespace Reference
provide functions that access the current thread of execution.
Functions
auto get_id () noexcept
Get the thread ID of the current thread.
void yield () noexcept
Yield the current thread.
template<class T_Rep , class T_Period >
void busy_wait_for (const std::chrono::duration< T_Rep, T_Period > &wait_duration)
Busy wait for a specified time duration.
template<class T_Rep , class T_Period >
auto sleep_for (const std::chrono::duration< T_Rep, T_Period > &sleep_duration)
Suspend the current thread for a specified time duration.
template<class T_Clock , class T_Duration >
void sleep_until (const std::chrono::time_point< T_Clock, T_Duration > &sleep_time)
Suspend the current thread until a specified time point.
void abort () noexcept
Abort the current thread.
void suspend () noexcept
Suspend the current thread.
thread_prio get_priority () noexcept
Get the current thread's priority.
void set_priority (thread_prio prio) noexcept
Set the current thread's priority.
Detailed Description
provide functions that access the current thread of execution.
Function Documentation
abort()
void zpp::this_thread::abort () inline noexcept
Abort the current thread.
Definition at line 104 of file thread.hpp.
 {
   k_thread_abort(k_current_get());
 }
busy_wait_for()
template<class T_Rep , class T_Period > void zpp::this_thread::busy_wait_for (const std::chrono::duration< T_Rep, T_Period > & wait_duration) inline
Busy wait for a specified time duration.
Parameters
wait_duration The time to busy wait
Definition at line 62 of file thread.hpp.
 {
   using namespace std::chrono;
   microseconds us = duration_cast<microseconds>(wait_duration);
   k_busy_wait(us.count());
 }
get_id()
auto zpp::this_thread::get_id () inline noexcept
Get the thread ID of the current thread.
Returns
The thread ID of the current thread.
Definition at line 42 of file thread.hpp.
 {
   return ::zpp::thread_id(k_current_get());
 }
Referenced by main(), and ZTEST().
get_priority()
thread_prio zpp::this_thread::get_priority () inline noexcept
Get the current thread's priority.
Returns
The priority of the current thread
Definition at line 122 of file thread.hpp.
 {
   return thread_prio( k_thread_priority_get(k_current_get()) );
 }
Referenced by ZTEST().
set_priority()
void zpp::this_thread::set_priority (thread_prio prio) inline noexcept
Set the current thread's priority.
Parameters
prio The new priority of the current thread
Definition at line 132 of file thread.hpp.
 {
   k_thread_priority_set(k_current_get(), prio.native_value());
 }
Referenced by ZTEST().
sleep_for()
template<class T_Rep , class T_Period > auto zpp::this_thread::sleep_for (const std::chrono::duration< T_Rep, T_Period > & sleep_duration) inline
Suspend the current thread for a specified time duration.
Parameters
wait_duration The time to sleep
Definition at line 77 of file thread.hpp.
 {
   auto res = k_sleep(to_timeout(sleep_duration));
   return std::chrono::milliseconds(res);
 }
References zpp::to_timeout().
Referenced by inc_count(), main(), and ZTEST().
sleep_until()
template<class T_Clock , class T_Duration > void zpp::this_thread::sleep_until (const std::chrono::time_point< T_Clock, T_Duration > & sleep_time) inline
Suspend the current thread until a specified time point.
Parameters
wait_duration The time point util the current thread will sleep
Definition at line 91 of file thread.hpp.
 {
   using namespace std::chrono;
   T_Duration dt;
   while ( (dt = sleep_time - T_Clock::now()) > T_Duration::zero()) {
     k_sleep(to_timeout(dt));
   }
 }
References zpp::to_timeout().
suspend()
void zpp::this_thread::suspend () inline noexcept
Suspend the current thread.
Definition at line 112 of file thread.hpp.
 {
   k_thread_suspend(k_current_get());
 }
yield()
void zpp::this_thread::yield () inline noexcept
Yield the current thread.
Definition at line 50 of file thread.hpp.
 {
   k_yield();
 }
Referenced by zpp::sem_base< T_Sem >::operator--(), and zpp::sem_base< T_Sem >::operator-=().