zpp: samples/hello_world/src/main.cpp File Reference
main.cpp File Reference
#include <zpp.hpp>
#include <chrono>
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 26 of file main.cpp.
 {
   //
   // use zpp and std::chrono namespaces in the function
   //
   using namespace zpp;
   using namespace std::chrono;
   mutex print_lock;
   //
   // Create thread attributes used for thread creation
   //
   const thread_attr my_thread_attr(
         thread_prio::preempt(0),
         thread_inherit_perms::no,
         thread_suspend::no
       );
   //
   // Create the first thread, using a lambda passing a const char* as
   // argument that is used as "template" for the print out.
   //
   // The lock used for making sure the prints don't get messed up
   // is captured by reference
   //
   const char* string_arg = "Hello World from thread tid={}\n";
   auto my_thread = thread(
     my_thread_tcb, my_thread_tstack(), my_thread_attr, &my_heap,
     [&print_lock](const char* t) noexcept
     {
       while (true) {
         //
         // Use a lock_guard in a scope to automatically
         // do the unlocking when leaving the scope
         //
         {
           lock_guard lg(print_lock);
           //
           // print the thread ID of this thread
           //
           print(t, this_thread::get_id());
         }
         //
         // let this thread sleep for 500 ms without
         // holding the lock
         //
         this_thread::sleep_for(500ms);
       }
     }, string_arg);
   //
   // Loop forever, because ending main would not only end the
   // program, my_thread would also go out of scope aborting the thread.
   //
   while (true) {
     // Use a lock_guard in a scope to automatically
     // do the unlocking when leaving the scope
     //
     {
       lock_guard lg(print_lock);
       //
       // print the thread ID of the main thread
       //
       print("Hello World from main tid={}\n",
               this_thread::get_id());
     }
     //
     // let main thread sleep for 1 s without holding the lock
     //
     this_thread::sleep_for(1s);
   }
   return 0;
 }
References zpp::this_thread::get_id(), zpp::no, zpp::thread_prio::preempt(), zpp::print(), and zpp::this_thread::sleep_for().