zpp: tests/print/src/main.cpp File Reference
main.cpp File Reference
#include <zephyr/ztest.h>
#include <zpp/fmt.hpp>
Functions
ZTEST_SUITE (zpp_print_tests, NULL, NULL, NULL, NULL, NULL)
ZTEST (zpp_print_tests, test_print_uint8_t)
ZTEST (zpp_print_tests, test_print_int8_t)
ZTEST (zpp_print_tests, test_print_uint16_t)
ZTEST (zpp_print_tests, test_print_int16_t)
ZTEST (zpp_print_tests, test_print_uint32_t)
ZTEST (zpp_print_tests, test_print_int32_t)
ZTEST (zpp_print_tests, test_print_uint64_t)
ZTEST (zpp_print_tests, test_print_int64_t)
ZTEST (zpp_print_tests, test_print_char)
ZTEST (zpp_print_tests, test_print_string)
ZTEST (zpp_print_tests, test_print_void_ptr)
Function Documentation
ZTEST() [1/11]
ZTEST (zpp_print_tests , test_print_char)
Definition at line 61 of file main.cpp.
 {
   char v{ 'c' };
   zpp::print("char {} == c\n", v);
 }
References zpp::print().
ZTEST() [2/11]
ZTEST (zpp_print_tests , test_print_int16_t)
Definition at line 31 of file main.cpp.
 {
   int16_t v{ -1234 };
   zpp::print("int16_t {} == -1234\n", v);
 }
References zpp::print().
ZTEST() [3/11]
ZTEST (zpp_print_tests , test_print_int32_t)
Definition at line 43 of file main.cpp.
 {
   int32_t v{ -12345678 };
   zpp::print("int32_t {} == -12345678\n", v);
 }
References zpp::print().
ZTEST() [4/11]
ZTEST (zpp_print_tests , test_print_int64_t)
Definition at line 55 of file main.cpp.
 {
   int64_t v{ -12345678901011 };
   zpp::print("int64_t {} == -12345678901011\n", v);
 }
References zpp::print().
ZTEST() [5/11]
ZTEST (zpp_print_tests , test_print_int8_t)
Definition at line 19 of file main.cpp.
 {
   int8_t v{ -12 };
   zpp::print("int8_t {} == -12\n", v);
 }
References zpp::print().
ZTEST() [6/11]
ZTEST (zpp_print_tests , test_print_string)
Definition at line 67 of file main.cpp.
 {
   const char* v{ "string" };
   zpp::print("const char* {} == string\n", v);
 }
References zpp::print().
ZTEST() [7/11]
ZTEST (zpp_print_tests , test_print_uint16_t)
Definition at line 25 of file main.cpp.
 {
   uint16_t v{ 1234 };
   zpp::print("uint16_t {} == 1234\n", v);
 }
References zpp::print().
ZTEST() [8/11]
ZTEST (zpp_print_tests , test_print_uint32_t)
Definition at line 37 of file main.cpp.
 {
   uint32_t v{ 12345678 };
   zpp::print("uint32_t {} == 12345678\n", v);
 }
References zpp::print().
ZTEST() [9/11]
ZTEST (zpp_print_tests , test_print_uint64_t)
Definition at line 49 of file main.cpp.
 {
   uint64_t v{ 12345678901011 };
   zpp::print("uint64_t {} == 12345678901011\n", v);
 }
References zpp::print().
ZTEST() [10/11]
ZTEST (zpp_print_tests , test_print_uint8_t)
Definition at line 13 of file main.cpp.
 {
   uint8_t v{ 12 };
   zpp::print("uint8_t {} == 12\n", v);
 }
References zpp::print().
ZTEST() [11/11]
ZTEST (zpp_print_tests , test_print_void_ptr)
Definition at line 73 of file main.cpp.
 {
   void* v{ (void*)0x12345678 };
   zpp::print("void* {} == 0x12345678\n", v);
 }
References zpp::print().
ZTEST_SUITE()
ZTEST_SUITE (zpp_print_tests , NULL , NULL , NULL , NULL , NULL)