zpp: tests/timer/src/main.cpp File Reference
main.cpp File Reference
#include <zephyr/ztest.h>
#include <zephyr/kernel.h>
#include <zpp/timer.hpp>
#include <zpp/thread.hpp>
#include <zpp/fmt.hpp>
Functions
ZTEST_SUITE (zpp_timer_tests, NULL, NULL, NULL, NULL, NULL)
ZTEST (zpp_timer_tests, test_timer_creation_function)
ZTEST (zpp_timer_tests, test_timer_creation_lambda)
Function Documentation
ZTEST() [1/2]
ZTEST (zpp_timer_tests , test_timer_creation_function)
Definition at line 28 of file main.cpp.
 {
   using namespace zpp;
   using namespace std::chrono;
   auto t = make_timer(timer_callback);
   t.start(100ms, 1s);
   this_thread::sleep_for(5s);
 }
References zpp::make_timer(), and zpp::this_thread::sleep_for().
ZTEST() [2/2]
ZTEST (zpp_timer_tests , test_timer_creation_lambda)
Definition at line 39 of file main.cpp.
 {
   using namespace zpp;
   using namespace std::chrono;
   auto t = make_timer(
     [] (auto t) {
       print("Hello from timer tid={}\n",
           this_thread::get_id());
     } );
   t.start(100ms, 1s);
   this_thread::sleep_for(5s);
 }
References zpp::this_thread::get_id(), zpp::make_timer(), zpp::print(), and zpp::this_thread::sleep_for().
ZTEST_SUITE()
ZTEST_SUITE (zpp_timer_tests , NULL , NULL , NULL , NULL , NULL)